import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, ChevronRight, Globe2, Grid2X2, ShieldCheck, UserRoundCheck, Zap } from 'lucide-react';
import { Brand } from '@/components/Brand';
import { ThemeToggle } from '@/components/ThemeToggle';
import { CurrencyHubConverter } from '@/components/CurrencyConverter';
import { LocalizedUi } from '@/components/LocalizedToolExperience';
import { ScaleLocalizedToolExperience } from '@/components/ScaleLocalizedToolExperience';
import { tools } from '@/data/tools';
import {
  getLocalizedPilotByToolId,
  getLocalizedPilotTool,
  localizedAlternates,
  localizedPath,
  localizedPilotTools,
  pilotLocaleMeta,
  type LocalizedPilotTool,
  type PilotLocale,
} from '@/data/localizedToolRegistry';

type Copy={home:string;tools:string;kicker:string;free:string;private:string;privateNote:string;instant:string;instantNote:string;noSignup:string;noSignupNote:string;why:string;about:string;related:string;relatedNote:string;faq:string;languages:string;open:string;guide:string;example:string;footerTagline:string;company:string;aboutLink:string;methodology:string;privacy:string;terms:string;nav:{currency:string;calculator:string;images:string;pdf:string;website:string}};

const copy:Record<PilotLocale,Copy>={
  de:{home:'Startseite',tools:'Tools',kicker:'KOSTENLOSES ONLINE-TOOL',free:'Kostenlos nutzbar',private:'Datenschutzorientiert',privateNote:'Browser-first, wenn technisch möglich',instant:'Schneller Workflow',instantNote:'Ohne Einrichtung direkt starten',noSignup:'Keine Anmeldung',noSignupNote:'Tool öffnen und Aufgabe erledigen',why:'VORTEILE',about:'ÜBER DIESES TOOL',related:'Passende Tools',relatedNote:'Weitere deutschsprachige Tools für denselben Workflow.',faq:'Häufige Fragen',languages:'Dieses Tool in anderen Sprachen',open:'Tool öffnen',guide:'PRAXIS',example:'TYPISCHER EINSATZ',footerTagline:'Schnelle, praktische Tools für den Alltag.',company:'Unternehmen',aboutLink:'Über Toolmera',methodology:'Methodik',privacy:'Datenschutz',terms:'Bedingungen',nav:{currency:'Währungen',calculator:'Rechner',images:'Bilder',pdf:'PDF',website:'Website'}},
  hi:{home:'होम',tools:'टूल्स',kicker:'मुफ्त ऑनलाइन टूल',free:'मुफ्त उपयोग',private:'प्राइवेसी-केंद्रित',privateNote:'जहाँ संभव हो, प्रोसेसिंग ब्राउज़र में',instant:'तेज़ काम',instantNote:'बिना सेटअप तुरंत शुरू करें',noSignup:'साइन-अप नहीं',noSignupNote:'टूल खोलें और काम पूरा करें',why:'मुख्य फायदे',about:'इस टूल के बारे में',related:'संबंधित टूल्स',relatedNote:'इसी काम से जुड़े दूसरे हिन्दी टूल्स।',faq:'सामान्य सवाल',languages:'यही टूल दूसरी भाषाओं में',open:'टूल खोलें',guide:'व्यावहारिक उपयोग',example:'आम उपयोग',footerTagline:'रोज़मर्रा के काम के लिए तेज़ और उपयोगी टूल्स।',company:'कंपनी',aboutLink:'Toolmera के बारे में',methodology:'मेथडोलॉजी',privacy:'प्राइवेसी',terms:'शर्तें',nav:{currency:'करेंसी',calculator:'कैलकुलेटर',images:'इमेज',pdf:'PDF',website:'वेबसाइट'}},
  ru:{home:'Главная',tools:'Инструменты',kicker:'БЕСПЛАТНЫЙ ОНЛАЙН-ИНСТРУМЕНТ',free:'Бесплатно',private:'Приватный подход',privateNote:'Обработка в браузере, где это возможно',instant:'Быстрый результат',instantNote:'Без настройки и лишних шагов',noSignup:'Без аккаунта',noSignupNote:'Откройте инструмент и выполните задачу',why:'ПРЕИМУЩЕСТВА',about:'ОБ ИНСТРУМЕНТЕ',related:'Связанные инструменты',relatedNote:'Другие русскоязычные инструменты для продолжения работы.',faq:'Частые вопросы',languages:'Этот инструмент на других языках',open:'Открыть',guide:'ПРАКТИКА',example:'ТИПИЧНЫЙ СЦЕНАРИЙ',footerTagline:'Быстрые и практичные инструменты для повседневных задач.',company:'Компания',aboutLink:'О Toolmera',methodology:'Методология',privacy:'Конфиденциальность',terms:'Условия',nav:{currency:'Валюты',calculator:'Калькуляторы',images:'Изображения',pdf:'PDF',website:'Сайты'}},
};

function localeHref(locale:PilotLocale,toolId:string){return localizedPath(locale,toolId)||`/${locale}/`}

function LocalizedHeader({locale}:{locale:PilotLocale}){
  const c=copy[locale];const nav=[[c.tools,`/${locale}/`],[c.nav.currency,localeHref(locale,'currency')],[c.nav.calculator,localeHref(locale,'percentage')],[c.nav.images,localeHref(locale,'compress-jpg')],[c.nav.pdf,localeHref(locale,'merge-pdf')],[c.nav.website,localeHref(locale,'website-analyzer')]];
  return <header className="siteHeader"><div className="shell headerInner"><Brand/><nav className="desktopNav" aria-label={c.tools}>{nav.map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</nav><div className="headerActions"><ThemeToggle/><Link className="allToolsButton" href={`/${locale}/`}><Grid2X2 size={16}/>{c.tools}</Link></div></div></header>;
}

function LocalizedFooter({locale}:{locale:PilotLocale}){
  const c=copy[locale];return <footer className="footer"><div className="shell footerGrid footerGridExpanded"><div className="footerBrand"><Brand/><p>{c.footerTagline}</p><span>{c.free} · {c.noSignup}</span></div><div className="footerColumn"><strong>{c.tools}</strong><Link href={`/${locale}/`}>{c.tools}</Link><Link href={localeHref(locale,'currency')}>{c.nav.currency}</Link><Link href={localeHref(locale,'percentage')}>{c.nav.calculator}</Link><Link href={localeHref(locale,'compress-jpg')}>{c.nav.images}</Link><Link href={localeHref(locale,'merge-pdf')}>{c.nav.pdf}</Link><Link href={localeHref(locale,'website-analyzer')}>{c.nav.website}</Link></div><div className="footerColumn"><strong>{c.company}</strong><Link href="/about/">{c.aboutLink}</Link><Link href="/methodology/">{c.methodology}</Link><Link href="/privacy/">{c.privacy}</Link><Link href="/terms/">{c.terms}</Link></div><div className="footerMeta"><span>© {new Date().getFullYear()} Toolmera</span><Link href="/en/">English</Link>{(['de','hi','ru'] as PilotLocale[]).filter(code=>code!==locale).map(code=><Link href={`/${code}/`} key={code}>{pilotLocaleMeta[code].nativeLabel}</Link>)}</div></div></footer>;
}

function relatedFor(locale:PilotLocale,toolId:string){
  const list=localizedPilotTools[locale];const currentIndex=list.findIndex(item=>item.toolId===toolId);const currentTool=tools.find(t=>t.id===toolId);const circular=currentIndex<0?list:[...list.slice(currentIndex+1),...list.slice(0,currentIndex)];const same=currentTool?circular.filter(item=>tools.find(t=>t.id===item.toolId)?.category===currentTool.category):[];const picks=[...same.slice(0,3),...circular.filter(item=>!same.includes(item))];return [...new Map(picks.map(item=>[item.toolId,item])).values()].slice(0,6);
}

function seoSections(locale:PilotLocale,item:LocalizedPilotTool){
  const benefits=item.benefits.join(' · ');const firstAnswer=item.faq[0]?.a||item.description;
  if(locale==='de')return[{k:copy.de.guide,title:`${item.name}: so funktioniert der Workflow`,body:`${item.intro} Die Seite ist auf genau diese Aufgabe ausgerichtet und vermeidet unnötige Zwischenschritte.`},{k:copy.de.example,title:`Was du mit ${item.name} direkt erledigen kannst`,body:`Wichtige Funktionen: ${benefits}. ${firstAnswer}`}];
  if(locale==='hi')return[{k:copy.hi.guide,title:`${item.name} का सही workflow`,body:`${item.intro} यह page इसी task पर focused है और अनावश्यक steps से बचता है।`},{k:copy.hi.example,title:`${item.name} में क्या कर सकते हैं`,body:`मुख्य सुविधाएँ: ${benefits}। ${firstAnswer}`}];
  return[{k:copy.ru.guide,title:`Как использовать ${item.name}`,body:`${item.intro} Страница сфокусирована на этой конкретной задаче без лишних промежуточных шагов.`},{k:copy.ru.example,title:`Что можно сделать в ${item.name}`,body:`Ключевые возможности: ${benefits}. ${firstAnswer}`}];
}

function LanguageLinks({locale,item}:{locale:PilotLocale;item:LocalizedPilotTool}){
  const languages=localizedAlternates(item.toolId,item.englishUrl);return <section className="shell workflowLinks"><span className="sectionKicker">{copy[locale].languages}</span><div>{Object.entries(languages).filter(([code])=>code!=='x-default').map(([code,url])=><a href={url} key={code} hrefLang={code}>{code==='en'?'English':pilotLocaleMeta[code as PilotLocale]?.nativeLabel||code}<ArrowRight size={14}/></a>)}</div></section>;
}

export function localizedScaleToolMetadata(locale:PilotLocale,slug:string):Metadata{
  const item=getLocalizedPilotTool(locale,slug);if(!item)return{};const meta=pilotLocaleMeta[locale];const canonical=`https://toolmera.com/${locale}/${item.slug}/`;
  return{title:item.title,description:item.description,alternates:{canonical,languages:localizedAlternates(item.toolId,item.englishUrl)},openGraph:{title:item.title,description:item.description,url:canonical,siteName:'Toolmera',type:'website',locale:meta.ogLocale},twitter:{card:'summary',title:item.title,description:item.description},other:{'content-language':meta.lang}};
}

export function localizedScaleHubMetadata(locale:PilotLocale):Metadata{
  const meta=pilotLocaleMeta[locale];const canonical=`https://toolmera.com/${locale}/`;return{title:meta.hubTitle,description:meta.hubDescription,alternates:{canonical,languages:{en:'https://toolmera.com/en/',de:'https://toolmera.com/de/',hi:'https://toolmera.com/hi/',ru:'https://toolmera.com/ru/','x-default':'https://toolmera.com/en/'}},openGraph:{title:meta.hubTitle,description:meta.hubDescription,url:canonical,siteName:'Toolmera',type:'website',locale:meta.ogLocale},twitter:{card:'summary',title:meta.hubTitle,description:meta.hubDescription},other:{'content-language':meta.lang}};
}

export function LocalizedScaleToolPage({locale,slug}:{locale:PilotLocale;slug:string}){
  const item=getLocalizedPilotTool(locale,slug);if(!item)return null;const meta=pilotLocaleMeta[locale];const c=copy[locale];const tool=item.toolId==='currency'?null:tools.find(t=>t.id===item.toolId&&!t.country);if(item.toolId!=='currency'&&!tool)return null;const canonical=`https://toolmera.com/${locale}/${item.slug}/`;const related=relatedFor(locale,item.toolId);const sections=seoSections(locale,item);
  const schemas:Record<string,unknown>[]=[{"@context":"https://schema.org","@type":"WebApplication",name:item.name,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",url:canonical,description:item.description,inLanguage:meta.lang,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:c.home,item:`https://toolmera.com/${locale}/`},{"@type":"ListItem",position:2,name:meta.nativeLabel,item:`https://toolmera.com/${locale}/`},{"@type":"ListItem",position:3,name:item.name,item:canonical}]}];
  return <><LocalizedHeader locale={locale}/><main className="subPage" lang={meta.lang}><section className="shell toolHero compactToolHero"><div className="breadcrumbs"><Link href={`/${locale}/`}>{c.home}</Link><ChevronRight/><Link href={`/${locale}/`}>{meta.nativeLabel}</Link><ChevronRight/><span>{item.name}</span></div><span className="eyebrow neonText">{c.kicker}</span><h1>{item.name}</h1><p>{item.intro}</p></section><LanguageLinks locale={locale} item={item}/><div className="shell">{item.toolId==='currency'?<LocalizedUi locale={locale}><CurrencyHubConverter/></LocalizedUi>:<ScaleLocalizedToolExperience tool={tool!} item={item} locale={locale}/>}</div><section className="shell toolTrustRow"><div><ShieldCheck/><span><strong>{c.private}</strong><small>{c.privateNote}</small></span></div><div><Zap/><span><strong>{c.instant}</strong><small>{c.instantNote}</small></span></div><div><UserRoundCheck/><span><strong>{c.noSignup}</strong><small>{c.noSignupNote}</small></span></div></section><section className="shell toolContent"><div><span className="sectionKicker">{c.why}</span><h2>{item.name}</h2><ul>{item.benefits.map(x=><li key={x}>{x}</li>)}</ul></div><div><span className="sectionKicker">{c.about}</span><h2>{item.title}</h2><p>{item.description}</p></div></section><section className="shell seoDeepDive">{sections.map(section=><article className="seoArticle" key={section.title}><span className="sectionKicker">{section.k}</span><h2>{section.title}</h2><p>{section.body}</p></article>)}</section><section className="shell section"><div className="sectionHead"><div><span className="sectionKicker">{c.related}</span><h2>{c.related}</h2><p>{c.relatedNote}</p></div></div><div className="categoryGrid">{related.map(next=><Link className="categoryCard accent-blue" href={`/${locale}/${next.slug}/`} key={next.toolId}><span className="categoryIcon"><Globe2 size={24}/></span><div><h3>{next.name}</h3><p>{next.intro}</p></div><span>{c.open} <ArrowRight size={14}/></span></Link>)}</div></section><section className="shell faqSection"><span className="sectionKicker">FAQ</span><h2>{c.faq}</h2>{item.faq.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</section>{schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>)}</main><LocalizedFooter locale={locale}/></>;
}

export function LocalizedScaleHub({locale}:{locale:PilotLocale}){
  const meta=pilotLocaleMeta[locale];const c=copy[locale];const items=localizedPilotTools[locale];const schemas=[{"@context":"https://schema.org","@type":"CollectionPage",name:meta.hubTitle,url:`https://toolmera.com/${locale}/`,description:meta.hubIntro,inLanguage:meta.lang},{"@context":"https://schema.org","@type":"ItemList",numberOfItems:items.length,itemListElement:items.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.name,url:`https://toolmera.com/${locale}/${item.slug}/`}))}];
  return <><LocalizedHeader locale={locale}/><main className="subPage" lang={meta.lang}><section className="shell categoryHero compactHero"><div className="breadcrumbs"><Link href={`/${locale}/`}>{c.home}</Link><ChevronRight/><span>{meta.nativeLabel}</span></div><span className="eyebrow neonText">TOOLMERA / {meta.nativeLabel}</span><h1>{meta.hubTitle}</h1><p>{meta.hubIntro}</p><div className="categoryMeta"><span>{items.length} tools</span><span>{c.free}</span><span>{c.noSignup}</span></div></section><section className="shell section"><div className="sectionHead"><div><span className="sectionKicker">{c.tools}</span><h2>{meta.hubTitle}</h2><p>{meta.hubDescription}</p></div></div><div className="categoryGrid">{items.map(item=><Link className="categoryCard accent-blue" href={`/${locale}/${item.slug}/`} key={item.toolId}><span className="categoryIcon"><Globe2 size={24}/></span><div><h3>{item.name}</h3><p>{item.intro}</p></div><span>{c.open} <ArrowRight size={14}/></span></Link>)}</div></section><section className="shell workflowLinks"><span className="sectionKicker">{c.languages}</span><div><Link href="/en/">English<ArrowRight size={14}/></Link>{(['de','hi','ru'] as PilotLocale[]).filter(code=>code!==locale).map(code=><Link href={`/${code}/`} key={code}>{pilotLocaleMeta[code].nativeLabel}<ArrowRight size={14}/></Link>)}</div></section>{schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>)}</main><LocalizedFooter locale={locale}/></>;
}
