import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, ChevronRight, Globe2, Grid2X2, ShieldCheck, UserRoundCheck, Zap } from 'lucide-react';
import { Brand } from '@/components/Brand';
import { ThemeToggle } from '@/components/ThemeToggle';
import { CurrencyHubConverter } from '@/components/CurrencyConverter';
import { LocalizedToolExperience, LocalizedUi } from '@/components/LocalizedToolExperience';
import { tools } from '@/data/tools';
import { getLocalizedPilotByToolId, getLocalizedPilotTool, localizedAlternates, localizedPath, localizedPilotTools, pilotLocaleMeta, type PilotLocale } from '@/data/localizedToolPilot';

type Guide={title:string;body:string;exampleTitle:string;example:string};

type LocaleCopy={
  home:string;tools:string;kicker:string;free:string;private:string;privateNote:string;instant:string;instantNote:string;noSignup:string;noSignupNote:string;why:string;about:string;related:string;relatedNote:string;faq:string;languages:string;english:string;open:string;guide:string;example:string;hubKicker:string;hubTitle:string;hubIntro:string;hubNote:string;footerTagline:string;company:string;aboutLink:string;methodology:string;privacy:string;terms:string;
  nav:{currency:string;calculator:string;images:string;pdf:string;website:string};
};

const copy:Record<PilotLocale,LocaleCopy>={
  de:{home:'Startseite',tools:'Tools',kicker:'KOSTENLOSES ONLINE-TOOL',free:'Kostenlos nutzbar',private:'Datenschutzorientiert',privateNote:'Browser-first, wenn technisch möglich',instant:'Schneller Workflow',instantNote:'Ohne Einrichtung direkt starten',noSignup:'Keine Anmeldung',noSignupNote:'Tool öffnen und Aufgabe erledigen',why:'VORTEILE',about:'ÜBER DIESES TOOL',related:'Passende Tools',relatedNote:'Weitere deutschsprachige Tools für denselben Workflow.',faq:'Häufige Fragen',languages:'Dieses Tool in anderen Sprachen',english:'English',open:'Tool öffnen',guide:'PRAXIS',example:'BEISPIEL',hubKicker:'TOOLMERA / DEUTSCH',hubTitle:'Kostenlose Online-Tools auf Deutsch',hubIntro:'15 ausgewählte Rechner, Konverter, Bild-, PDF- und Website-Tools mit deutschsprachiger Oberfläche, verständlichen Erklärungen und direkter Nutzung im Browser.',hubNote:'Wähle ein Tool und arbeite in derselben Sprachversion weiter. Jede Seite ist auf den konkreten Such- und Nutzungszweck des Tools ausgerichtet.',footerTagline:'Schnelle, praktische Tools für den Alltag.',company:'Unternehmen',aboutLink:'Über Toolmera',methodology:'Methodik',privacy:'Datenschutz',terms:'Bedingungen',nav:{currency:'Währungen',calculator:'Rechner',images:'Bilder',pdf:'PDF',website:'Website'}},
  hi:{home:'होम',tools:'टूल्स',kicker:'मुफ्त ऑनलाइन टूल',free:'मुफ्त उपयोग',private:'प्राइवेसी-केंद्रित',privateNote:'जहाँ संभव हो, प्रोसेसिंग ब्राउज़र में',instant:'तेज़ काम',instantNote:'बिना सेटअप तुरंत शुरू करें',noSignup:'साइन-अप नहीं',noSignupNote:'टूल खोलें और काम पूरा करें',why:'मुख्य फायदे',about:'इस टूल के बारे में',related:'संबंधित टूल्स',relatedNote:'इसी काम से जुड़े दूसरे हिन्दी टूल्स।',faq:'सामान्य सवाल',languages:'यही टूल दूसरी भाषाओं में',english:'English',open:'टूल खोलें',guide:'कैसे उपयोग करें',example:'उदाहरण',hubKicker:'TOOLMERA / हिन्दी',hubTitle:'हिन्दी में मुफ्त ऑनलाइन टूल्स',hubIntro:'15 चुने हुए कैलकुलेटर, कन्वर्टर, इमेज, PDF और वेबसाइट टूल्स हिन्दी इंटरफ़ेस, साफ़ निर्देश और ब्राउज़र-आधारित वर्कफ़्लो के साथ।',hubNote:'हर पेज एक स्पष्ट काम पर केंद्रित है। टूल चुनें और उसी भाषा में जुड़े हुए दूसरे टूल्स पर जाएँ।',footerTagline:'रोज़मर्रा के काम के लिए तेज़ और उपयोगी टूल्स।',company:'कंपनी',aboutLink:'Toolmera के बारे में',methodology:'मेथडोलॉजी',privacy:'प्राइवेसी',terms:'शर्तें',nav:{currency:'करेंसी',calculator:'कैलकुलेटर',images:'इमेज',pdf:'PDF',website:'वेबसाइट'}},
  ru:{home:'Главная',tools:'Инструменты',kicker:'БЕСПЛАТНЫЙ ОНЛАЙН-ИНСТРУМЕНТ',free:'Бесплатно',private:'Приватный подход',privateNote:'Обработка в браузере, где это возможно',instant:'Быстрый результат',instantNote:'Без настройки и лишних шагов',noSignup:'Без аккаунта',noSignupNote:'Откройте инструмент и выполните задачу',why:'ПРЕИМУЩЕСТВА',about:'ОБ ИНСТРУМЕНТЕ',related:'Связанные инструменты',relatedNote:'Другие русскоязычные инструменты для продолжения работы.',faq:'Частые вопросы',languages:'Этот инструмент на других языках',english:'English',open:'Открыть',guide:'КАК ИСПОЛЬЗОВАТЬ',example:'ПРИМЕР',hubKicker:'TOOLMERA / РУССКИЙ',hubTitle:'Бесплатные онлайн-инструменты на русском',hubIntro:'15 выбранных калькуляторов, конвертеров, инструментов для изображений, PDF и сайтов с русскоязычным интерфейсом и понятными пояснениями.',hubNote:'Каждая страница решает конкретную задачу и связана с другими русскоязычными инструментами того же рабочего процесса.',footerTagline:'Быстрые и практичные инструменты для повседневных задач.',company:'Компания',aboutLink:'О Toolmera',methodology:'Методология',privacy:'Конфиденциальность',terms:'Условия',nav:{currency:'Валюты',calculator:'Калькуляторы',images:'Изображения',pdf:'PDF',website:'Сайты'}},
};

const guides:Record<PilotLocale,Record<string,Guide>>={
  de:{
    currency:{title:'Wechselkurse schnell vergleichen',body:'Der Währungsrechner eignet sich für Reisen, internationale Rechnungen und schnelle Preisvergleiche. Entscheidend ist das Kursdatum: Toolmera zeigt den gespeicherten Referenzkurs mit Zeitbezug statt einen erfundenen Echtzeitkurs.',exampleTitle:'100 USD in EUR umrechnen',example:'Wähle USD als Ausgangswährung, EUR als Zielwährung und gib 100 ein. Das Ergebnis wird aus dem zuletzt gespeicherten Referenzkurs berechnet.'},
    percentage:{title:'Prozentwert, Anteil und Veränderung richtig unterscheiden',body:'Ein Prozentrechner löst mehrere unterschiedliche Aufgaben. Du kannst bestimmen, wie viel Prozent ein Wert vom Gesamtwert ausmacht, einen Prozentwert berechnen oder eine prozentuale Erhöhung beziehungsweise Verringerung vergleichen.',exampleTitle:'Preissteigerung berechnen',example:'Steigt ein Preis von 80 auf 92, wähle den Modus für prozentuale Veränderung. Der Rechner verwendet den Ausgangswert als Basis und zeigt die Veränderung in Prozent.'},
    'date-calculator':{title:'Kalenderdaten statt pauschaler Tagesblöcke',body:'Der Datumsrechner arbeitet mit echten Kalenderdaten. Dadurch werden unterschiedliche Monatslängen beim Addieren oder Subtrahieren von Monaten und Jahren berücksichtigt.',exampleTitle:'Sechs Wochen zu einem Datum addieren',example:'Wähle das Startdatum, trage 6 bei Wochen ein und addiere den Zeitraum. Das Tool zeigt das resultierende Datum und den Wochentag.'},
    'qr-code':{title:'QR-Codes für Links und Text erstellen',body:'Der Generator erzeugt statische QR-Codes direkt im Browser. Farben, Rand und Fehlerkorrektur lassen sich anpassen; PNG eignet sich für schnelle Nutzung, SVG für skalierbare Layouts.',exampleTitle:'QR-Code für eine Website',example:'Füge die vollständige URL ein, prüfe den Kontrast zwischen Vorder- und Hintergrund und exportiere anschließend PNG oder SVG.'},
    password:{title:'Zufällige Passwörter lokal erzeugen',body:'Der Passwort-Generator nutzt die Browser-Kryptografie und erlaubt die Auswahl von Länge, Groß- und Kleinbuchstaben, Ziffern und Sonderzeichen. Das Ergebnis wird lokal erstellt.',exampleTitle:'Starkes Passwort mit 24 Zeichen',example:'Stelle die Länge auf 24 und aktiviere mehrere Zeichengruppen. Mit „Passwort neu erzeugen“ erhältst du einen neuen zufälligen Wert.'},
    'png-webp':{title:'PNG für Web-Workflows in WebP umwandeln',body:'WebP kann Bilder für Websites kompakter bereitstellen und unterstützt Transparenz. Die Konvertierung eignet sich besonders für UI-Grafiken, Screenshots und transparente Assets.',exampleTitle:'Transparentes PNG konvertieren',example:'Lade das PNG in den Browser, starte die Konvertierung und prüfe das WebP-Ergebnis vor dem Download.'},
    'jpg-webp':{title:'JPG-Fotos als WebP ausgeben',body:'Die Konvertierung von JPG zu WebP ist für weboptimierte Foto-Assets gedacht. Über die Qualitätssteuerung lässt sich ein sinnvoller Kompromiss zwischen Dateigröße und sichtbarer Qualität wählen.',exampleTitle:'Produktfoto fürs Web',example:'Lade ein JPG hoch, reduziere die Qualität schrittweise und vergleiche das Ergebnis, bevor du die WebP-Datei speicherst.'},
    'compress-jpg':{title:'JPEG-Dateigröße ohne Formatwechsel reduzieren',body:'Dieses Tool behält JPG als Ausgabeformat bei. Du kannst die Qualität anpassen und die Dateigröße vor und nach der Komprimierung direkt vergleichen.',exampleTitle:'Großes Foto verkleinern',example:'Wähle das JPG, starte mit einer moderaten Qualitätsstufe und senke sie nur so weit, bis Dateigröße und Bildqualität für deinen Zweck passen.'},
    'resize-image':{title:'Bilder auf feste Pixelmaße skalieren',body:'Die Größenänderung ist für Websites, Social Media und Dokumente gedacht. Mit aktiviertem Seitenverhältnis bleibt die Bildgeometrie proportional.',exampleTitle:'Bild auf 1200 Pixel Breite setzen',example:'Trage 1200 als Breite ein und lasse das Seitenverhältnis aktiv, damit die passende Höhe automatisch abgeleitet wird.'},
    'merge-pdf':{title:'Mehrere PDF-Dateien in eine Reihenfolge bringen',body:'Beim Zusammenfügen kannst du mehrere PDFs auswählen und vor dem Export sortieren. Die Reihenfolge der Dateien bestimmt die Reihenfolge im fertigen Dokument.',exampleTitle:'Angebot und Anlagen verbinden',example:'Füge zuerst das Hauptdokument, danach die Anhänge hinzu, kontrolliere die Reihenfolge und exportiere anschließend eine gemeinsame PDF.'},
    'remove-duplicate-lines':{title:'Listen ohne doppelte Einträge bereinigen',body:'Das Tool eignet sich für Keywords, URLs, IDs und andere zeilenbasierte Daten. Groß-/Kleinschreibung, Leerzeichen und Sortierung lassen sich passend zum Datensatz steuern.',exampleTitle:'URL-Liste deduplizieren',example:'Füge eine URL pro Zeile ein, aktiviere bei Bedarf das Trimmen von Leerzeichen und entferne doppelte Zeilen, ohne das erste Vorkommen zu verlieren.'},
    length:{title:'Metrische und imperiale Längen vergleichen',body:'Der Längenumrechner verbindet Meter, Kilometer, Zentimeter und Millimeter mit Fuß, Zoll, Yard und Meilen. So lassen sich technische und alltägliche Maße direkt vergleichen.',exampleTitle:'Meter in Fuß umrechnen',example:'Gib den Meterwert ein, wähle Meter als Ausgangseinheit und Fuß als Zieleinheit. Das Ergebnis wird mit dem festen Umrechnungsfaktor berechnet.'},
    speed:{title:'Geschwindigkeit zwischen fünf Einheiten umrechnen',body:'Für Straße, Luftfahrt, Schifffahrt und technische Berechnungen stehen km/h, mph, m/s, ft/s und Knoten zur Verfügung. Die Umrechnung basiert auf festen mathematischen Faktoren.',exampleTitle:'100 km/h in mph',example:'Wähle km/h als Ausgangseinheit und mph als Ziel. Der Rechner zeigt den äquivalenten Wert und die Vergleichswerte der übrigen Einheiten.'},
    'sitemap-checker':{title:'XML-Sitemaps technisch prüfen',body:'Der Sitemap Checker kontrolliert Erreichbarkeit, Sitemap-Typ, URL-Anzahl, lastmod-Abdeckung und Beispiel-URLs. So lassen sich grundlegende technische Probleme einer öffentlichen Sitemap schnell erkennen.',exampleTitle:'sitemap.xml kontrollieren',example:'Füge die vollständige öffentliche Sitemap-URL ein und prüfe HTTP-Status, erkannte Einträge und lastmod-Signale.'},
    'website-analyzer':{title:'Öffentliche Seitensignale in einem Audit bündeln',body:'Die Website-Analyse prüft verifizierbare On-Page-, HTTP-, Crawl-, Security- und Technologie-Signale einer öffentlichen URL. Sie zeigt keine erfundenen Rankings oder privaten Search-Console-Daten.',exampleTitle:'Startseite technisch prüfen',example:'Gib die öffentliche HTTPS-URL ein und arbeite die Hinweise zu Metadaten, H1, robots.txt, Sitemap und Security Headern einzeln durch.'}
  },
  hi:{
    currency:{title:'करेंसी रेट को साफ़ तरीके से समझें',body:'करेंसी कन्वर्टर यात्रा, अंतरराष्ट्रीय भुगतान और कीमतों की तुलना जैसे कामों के लिए उपयोगी है। Toolmera उपलब्ध संदर्भ दर और उसकी तारीख दिखाता है ताकि परिणाम का समय-संदर्भ स्पष्ट रहे।',exampleTitle:'100 USD को INR में बदलना',example:'USD को source, INR को target चुनें और 100 राशि डालें। परिणाम उपलब्ध stored reference rate से निकाला जाएगा।'},
    percentage:{title:'प्रतिशत के अलग-अलग सवाल एक ही जगह हल करें',body:'प्रतिशत निकालना, किसी संख्या का प्रतिशत जानना, प्रतिशत बढ़ोतरी या कमी और दो मानों का प्रतिशत अंतर अलग calculations हैं। टूल में हर सवाल के लिए अलग mode है।',exampleTitle:'कीमत में बढ़ोतरी का प्रतिशत',example:'यदि कीमत 800 से 920 हो गई है, शुरुआती मान 800 और नया मान 920 डालकर increase/decrease mode चुनें।'},
    'date-calculator':{title:'असल कैलेंडर तारीखों के साथ गणना',body:'डेट कैलकुलेटर दिन, हफ्ते, महीने और साल जोड़ते या घटाते समय वास्तविक calendar dates का उपयोग करता है, इसलिए अलग-अलग महीनों की लंबाई सही तरह संभाली जाती है।',exampleTitle:'तारीख में 45 दिन जोड़ें',example:'शुरुआती तारीख चुनें, Days में 45 डालें और Add चुनें। टूल नई तारीख और weekday दिखाएगा।'},
    'qr-code':{title:'URL या टेक्स्ट का QR कोड बनाएँ',body:'QR कोड ब्राउज़र में बनता है और रंग, margin तथा error correction बदले जा सकते हैं। PNG जल्दी उपयोग के लिए और SVG scalable design के लिए उपयोगी है।',exampleTitle:'वेबसाइट लिंक का QR',example:'पूरा URL डालें, foreground और background में पर्याप्त contrast रखें और PNG या SVG डाउनलोड करें।'},
    password:{title:'ब्राउज़र में random password बनाएँ',body:'पासवर्ड जनरेटर browser Web Crypto का उपयोग करता है। आप length, uppercase, lowercase, digits और symbols चुन सकते हैं और नया password लोकल रूप से बना सकते हैं।',exampleTitle:'24 अक्षरों का मजबूत password',example:'Length 24 रखें, कई character groups चालू करें और नया password generate करें।'},
    'png-webp':{title:'PNG को वेब के लिए WebP में बदलें',body:'WebP web assets के लिए छोटा output दे सकता है और transparency को support करता है। यह screenshots, UI graphics और transparent images के लिए उपयोगी workflow है।',exampleTitle:'Transparent PNG convert करें',example:'PNG चुनें, conversion चलाएँ और download से पहले WebP output को जाँचें।'},
    'jpg-webp':{title:'JPG फोटो को WebP में बदलें',body:'JPG से WebP conversion web delivery के लिए उपयोगी है। Quality control से file size और visual quality के बीच सही balance चुना जा सकता है।',exampleTitle:'Product image को WebP करें',example:'JPG upload करें, quality को धीरे-धीरे adjust करें और acceptable result मिलने पर WebP डाउनलोड करें।'},
    'compress-jpg':{title:'JPG format रखते हुए file size घटाएँ',body:'यह tool output को JPG ही रखता है और quality control देता है। Before/after size देखकर compression level चुनना आसान होता है।',exampleTitle:'बड़ी JPG फोटो compress करें',example:'फोटो चुनें, मध्यम quality से शुरू करें और केवल उतना compress करें जितना आपके उपयोग के लिए जरूरी हो।'},
    'resize-image':{title:'Image को exact pixel size में resize करें',body:'Website, social post या document के लिए width और height बदली जा सकती है। Aspect ratio चालू रखने पर image proportion नहीं बिगड़ता।',exampleTitle:'Image width 1200 px करें',example:'Width में 1200 डालें और aspect ratio चालू रखें; height उसी अनुपात में बदल जाएगी।'},
    'merge-pdf':{title:'कई PDF को एक document में जोड़ें',body:'Merge PDF workflow में कई files चुनकर उनकी order बदली जा सकती है। Final document में वही क्रम रखा जाता है जो export से पहले दिखता है।',exampleTitle:'Report और annexures जोड़ें',example:'पहले main report, फिर annexures जोड़ें, order जाँचें और एक combined PDF बनाएँ।'},
    'remove-duplicate-lines':{title:'Duplicate lines हटाकर list साफ़ करें',body:'Keywords, URLs, IDs और line-based exports को clean करने के लिए case, whitespace, blank lines और sorting controls उपलब्ध हैं।',exampleTitle:'Keyword list deduplicate करें',example:'हर keyword नई line पर paste करें और duplicate removal चलाएँ; जरूरत हो तो case-insensitive comparison चुनें।'},
    length:{title:'Metric और imperial length units बदलें',body:'मीटर, किलोमीटर, सेंटीमीटर और मिलीमीटर को feet, inches, yards और miles के साथ convert किया जा सकता है।',exampleTitle:'मीटर से feet',example:'From में meter, To में foot चुनें और value डालें। परिणाम fixed conversion factor से निकलेगा।'},
    speed:{title:'Road से aviation तक speed conversion',body:'km/h, mph, m/s, ft/s और knots एक ही converter में उपलब्ध हैं। Conversion fixed mathematical factors पर आधारित है।',exampleTitle:'100 km/h को mph में बदलें',example:'km/h को source और mph को target चुनें; converter equivalent speed दिखाएगा।'},
    'sitemap-checker':{title:'XML sitemap की technical health जाँचें',body:'Tool public sitemap की availability, structure, URL count, sitemap index और lastmod coverage जैसे signals जाँचता है।',exampleTitle:'sitemap.xml test करें',example:'पूरी public sitemap URL डालें और HTTP response, entries और lastmod coverage देखें।'},
    'website-analyzer':{title:'Public website signals का practical audit',body:'Website Analyzer on-page SEO, HTTP, crawlability, robots.txt, sitemap, security headers और technology fingerprints जैसे verifiable signals जाँचता है।',exampleTitle:'Homepage audit करें',example:'Public HTTPS URL डालें और metadata, H1, crawl files तथा security findings को एक-एक करके review करें।'}
  },
  ru:{
    currency:{title:'Быстро сравнивайте валюты по справочному курсу',body:'Конвертер полезен для поездок, международных платежей и сравнения цен. Toolmera показывает доступный справочный курс с датой, поэтому результат не маскируется под биржевую котировку в реальном времени.',exampleTitle:'Перевести 100 USD в EUR',example:'Выберите USD как исходную валюту, EUR как целевую и введите 100. Сумма будет рассчитана по последнему сохранённому справочному курсу.'},
    percentage:{title:'Разные задачи на проценты — разные формулы',body:'Калькулятор умеет находить долю в процентах, процент от числа, процентное изменение и процентную разницу. Это позволяет не смешивать разные типы расчёта в одной формуле.',exampleTitle:'Посчитать рост цены',example:'Если цена выросла с 800 до 920, укажите 800 как начальное значение и 920 как новое, затем выберите режим роста/снижения.'},
    'date-calculator':{title:'Расчёты по реальному календарю',body:'Калькулятор дат добавляет или вычитает дни, недели, месяцы и годы с учётом фактической длины месяцев, а не условных 30 дней.',exampleTitle:'Добавить шесть недель',example:'Выберите исходную дату, укажите 6 недель и режим добавления. Инструмент покажет итоговую дату и день недели.'},
    'qr-code':{title:'Создавайте QR-коды для ссылок и текста',body:'Статический QR-код формируется в браузере. Можно настроить цвет, отступ и уровень коррекции ошибок, а затем скачать PNG или SVG.',exampleTitle:'QR-код на страницу сайта',example:'Вставьте полный URL, убедитесь в хорошем контрасте цветов и экспортируйте готовый код в нужном формате.'},
    password:{title:'Генерируйте случайные пароли локально',body:'Генератор использует Web Crypto в браузере и позволяет выбрать длину, регистр, цифры и специальные символы. Значение создаётся локально.',exampleTitle:'Пароль длиной 24 символа',example:'Установите длину 24, включите несколько групп символов и нажмите создание нового пароля.'},
    'png-webp':{title:'Конвертируйте PNG в современный WebP',body:'WebP подходит для веб-графики и поддерживает прозрачность. Такой формат часто удобен для интерфейсных изображений, скриншотов и прозрачных элементов.',exampleTitle:'PNG с прозрачным фоном',example:'Выберите PNG, запустите конвертацию и проверьте полученный WebP перед скачиванием.'},
    'jpg-webp':{title:'Преобразуйте фотографии JPG в WebP',body:'Конвертация в WebP помогает подготовить фото для веб-использования. Настройка качества позволяет подобрать баланс между размером файла и визуальным результатом.',exampleTitle:'Фото товара для сайта',example:'Загрузите JPG, постепенно меняйте качество и сохраните WebP, когда размер и внешний вид вас устраивают.'},
    'compress-jpg':{title:'Уменьшайте JPG без смены формата',body:'Инструмент сохраняет формат JPG и даёт управлять качеством сжатия. Размер до и после обработки можно сравнить прямо на странице.',exampleTitle:'Сжать большую фотографию',example:'Начните со среднего качества и уменьшайте его только до уровня, который сохраняет приемлемый вид изображения.'},
    'resize-image':{title:'Изменяйте изображение до точных размеров',body:'Можно задать ширину и высоту в пикселях для сайта, соцсетей или документа. При сохранении пропорций вторая сторона рассчитывается автоматически.',exampleTitle:'Сделать ширину 1200 px',example:'Введите 1200 в поле ширины и оставьте сохранение пропорций включённым.'},
    'merge-pdf':{title:'Собирайте несколько PDF в один файл',body:'Перед объединением файлы можно расположить в нужном порядке. Итоговый PDF сохранит выбранную последовательность документов.',exampleTitle:'Объединить отчёт и приложения',example:'Добавьте основной отчёт первым, приложения — следом, проверьте порядок и создайте один PDF.'},
    'remove-duplicate-lines':{title:'Очищайте списки от повторяющихся строк',body:'Подходит для ключевых слов, URL, ID и экспортов. Можно учитывать регистр, убирать пробелы, пустые строки и при необходимости сортировать результат.',exampleTitle:'Очистить список URL',example:'Вставьте по одному URL на строку, включите удаление пробелов при необходимости и удалите дубли, сохранив первое вхождение.'},
    length:{title:'Переводите метрические и имперские единицы длины',body:'Конвертер связывает метры, километры, сантиметры и миллиметры с футами, дюймами, ярдами и милями.',exampleTitle:'Метры в футы',example:'Выберите метры как исходную единицу, футы как целевую и введите значение.'},
    speed:{title:'Конвертируйте скорость для дороги, авиации и моря',body:'Поддерживаются km/h, mph, m/s, ft/s и узлы. Все результаты рассчитываются по фиксированным математическим коэффициентам.',exampleTitle:'100 km/h в mph',example:'Выберите km/h в поле «Из» и mph в поле «В» — инструмент покажет эквивалентную скорость.'},
    'sitemap-checker':{title:'Проверяйте техническое состояние XML Sitemap',body:'Sitemap Checker анализирует доступность, тип sitemap, количество URL, lastmod и примеры записей. Это помогает быстро найти базовые технические проблемы.',exampleTitle:'Проверить sitemap.xml',example:'Вставьте полный публичный URL sitemap и посмотрите HTTP-статус, найденные записи и покрытие lastmod.'},
    'website-analyzer':{title:'Собирайте проверяемые сигналы сайта в одном аудите',body:'Website Analyzer проверяет публичные on-page, HTTP, crawl, security и technology signals. Он не подменяет Search Console и не придумывает позиции.',exampleTitle:'Проверить главную страницу',example:'Введите публичный HTTPS URL и последовательно проверьте metadata, H1, robots.txt, sitemap и security headers.'}
  }
};

function localeHref(locale:PilotLocale,toolId:string){return localizedPath(locale,toolId)||`/${locale}/`}

function LocalizedHeader({locale}:{locale:PilotLocale}){
  const c=copy[locale];
  const nav=[
    [c.tools,`/${locale}/`],
    [c.nav.currency,localeHref(locale,'currency')],
    [c.nav.calculator,localeHref(locale,'percentage')],
    [c.nav.images,localeHref(locale,'compress-jpg')],
    [c.nav.pdf,localeHref(locale,'merge-pdf')],
    [c.nav.website,localeHref(locale,'website-analyzer')],
  ];
  return <header className="siteHeader"><div className="shell headerInner"><Brand/><nav className="desktopNav" aria-label={c.tools}>{nav.map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</nav><div className="headerActions"><ThemeToggle/><Link className="allToolsButton" href={`/${locale}/`}><Grid2X2 size={16}/>{c.tools}</Link></div></div></header>;
}

function LocalizedFooter({locale}:{locale:PilotLocale}){
  const c=copy[locale];
  return <footer className="footer"><div className="shell footerGrid footerGridExpanded">
    <div className="footerBrand"><Brand/><p>{c.footerTagline}</p><span>{c.free} · {c.noSignup}</span></div>
    <div className="footerColumn"><strong>{c.tools}</strong><Link href={`/${locale}/`}>{c.tools}</Link><Link href={localeHref(locale,'currency')}>{c.nav.currency}</Link><Link href={localeHref(locale,'percentage')}>{c.nav.calculator}</Link><Link href={localeHref(locale,'compress-jpg')}>{c.nav.images}</Link><Link href={localeHref(locale,'merge-pdf')}>{c.nav.pdf}</Link><Link href={localeHref(locale,'website-analyzer')}>{c.nav.website}</Link></div>
    <div className="footerColumn"><strong>{c.company}</strong><Link href="/about/">{c.aboutLink}</Link><Link href="/methodology/">{c.methodology}</Link><Link href="/privacy/">{c.privacy}</Link><Link href="/terms/">{c.terms}</Link></div>
    <div className="footerMeta"><span>© {new Date().getFullYear()} Toolmera</span><Link href="/en/">English</Link>{(['de','hi','ru'] as PilotLocale[]).filter(code=>code!==locale).map(code=><Link href={`/${code}/`} key={code}>{pilotLocaleMeta[code].nativeLabel}</Link>)}</div>
  </div></footer>;
}

export function localizedToolMetadata(locale:PilotLocale,slug:string):Metadata{
  const item=getLocalizedPilotTool(locale,slug);if(!item)return{};
  const meta=pilotLocaleMeta[locale];const canonical=`https://toolmera.com/${locale}/${item.slug}/`;
  return{title:item.title,description:item.description,alternates:{canonical,languages:localizedAlternates(item.toolId,item.englishUrl)},openGraph:{title:item.title,description:item.description,url:canonical,siteName:'Toolmera',type:'website',locale:meta.ogLocale},twitter:{card:'summary',title:item.title,description:item.description},other:{'content-language':meta.lang}};
}

export function localizedHubMetadata(locale:PilotLocale):Metadata{
  const meta=pilotLocaleMeta[locale];const c=copy[locale];const canonical=`https://toolmera.com/${locale}/`;
  return{title:c.hubTitle,description:c.hubIntro,alternates:{canonical,languages:{en:'https://toolmera.com/en/',de:'https://toolmera.com/de/',hi:'https://toolmera.com/hi/',ru:'https://toolmera.com/ru/','x-default':'https://toolmera.com/en/'}},openGraph:{title:c.hubTitle,description:c.hubIntro,url:canonical,siteName:'Toolmera',type:'website',locale:meta.ogLocale},twitter:{card:'summary',title:c.hubTitle,description:c.hubIntro},other:{'content-language':meta.lang}};
}

function languageVersions(toolId:string,englishUrl:string){
  const englishName=toolId==='currency'?'Currency Converter':tools.find(t=>t.id===toolId)?.name||'English';
  return [{code:'en',label:`English — ${englishName}`,href:englishUrl},...(['de','hi','ru'] as PilotLocale[]).map(locale=>{const item=getLocalizedPilotByToolId(locale,toolId);return item?{code:locale,label:`${pilotLocaleMeta[locale].nativeLabel} — ${item.name}`,href:`/${locale}/${item.slug}/`}:null}).filter((v):v is {code:string;label:string;href:string}=>Boolean(v))];
}

function LanguageLinks({locale,toolId,englishUrl}:{locale:PilotLocale;toolId:string;englishUrl:string}){
  const c=copy[locale];const current=localizedPath(locale,toolId);
  return <section className="shell workflowLinks" aria-label={c.languages}><span className="sectionKicker">{c.languages}</span><div>{languageVersions(toolId,englishUrl).map(item=><Link href={item.href} key={item.code} aria-current={item.href===current?'page':undefined}>{item.label}<ArrowRight size={14}/></Link>)}</div></section>;
}

function relatedFor(locale:PilotLocale,toolId:string){
  const list=localizedPilotTools[locale];const currentIndex=list.findIndex(item=>item.toolId===toolId);const currentTool=tools.find(t=>t.id===toolId);
  const circular=currentIndex<0?list:[...list.slice(currentIndex+1),...list.slice(0,currentIndex)];
  const same=currentTool?circular.filter(item=>tools.find(t=>t.id===item.toolId)?.category===currentTool.category):[];
  const picks=[...same.slice(0,2),...circular.filter(item=>!same.includes(item))];
  return [...new Map(picks.map(item=>[item.toolId,item])).values()].slice(0,4);
}

export function LocalizedPilotToolPage({locale,slug}:{locale:PilotLocale;slug:string}){
  const item=getLocalizedPilotTool(locale,slug);if(!item)return null;
  const meta=pilotLocaleMeta[locale];const c=copy[locale];const guide=guides[locale][item.toolId];
  const tool=item.toolId==='currency'?null:tools.find(t=>t.id===item.toolId&&!t.country);if(item.toolId!=='currency'&&!tool)return null;
  const canonical=`https://toolmera.com/${locale}/${item.slug}/`;const related=relatedFor(locale,item.toolId);
  const schemas:Record<string,unknown>[]=[
    {"@context":"https://schema.org","@type":"WebApplication",name:item.name,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",url:canonical,description:item.description,inLanguage:meta.lang,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},
    {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:c.home,item:`https://toolmera.com/${locale}/`},{"@type":"ListItem",position:2,name:meta.nativeLabel,item:`https://toolmera.com/${locale}/`},{"@type":"ListItem",position:3,name:item.name,item:canonical}]},
  ];
  return <><LocalizedHeader locale={locale}/><main className="subPage" lang={meta.lang}>
    <section className="shell toolHero compactToolHero"><div className="breadcrumbs"><Link href={`/${locale}/`}>{c.home}</Link><ChevronRight/><Link href={`/${locale}/`}>{meta.nativeLabel}</Link><ChevronRight/><span>{item.name}</span></div><span className="eyebrow neonText">{c.kicker}</span><h1>{item.name}</h1><p>{item.intro}</p></section>
    <LanguageLinks locale={locale} toolId={item.toolId} englishUrl={item.englishUrl}/>
    <div className="shell">{item.toolId==='currency'?<LocalizedUi locale={locale}><CurrencyHubConverter/></LocalizedUi>:<LocalizedToolExperience tool={tool!} locale={locale}/>}</div>
    <section className="shell toolTrustRow"><div><ShieldCheck/><span><strong>{c.private}</strong><small>{c.privateNote}</small></span></div><div><Zap/><span><strong>{c.instant}</strong><small>{c.instantNote}</small></span></div><div><UserRoundCheck/><span><strong>{c.noSignup}</strong><small>{c.noSignupNote}</small></span></div></section>
    <section className="shell toolContent"><div><span className="sectionKicker">{c.why}</span><h2>{item.name}</h2><ul>{item.benefits.map(x=><li key={x}>{x}</li>)}</ul></div><div><span className="sectionKicker">{c.about}</span><h2>{item.title}</h2><p>{item.description}</p></div></section>
    {guide&&<section className="shell seoDeepDive"><article className="seoArticle"><span className="sectionKicker">{c.guide}</span><h2>{guide.title}</h2><p>{guide.body}</p></article><article className="seoArticle"><span className="sectionKicker">{c.example}</span><h2>{guide.exampleTitle}</h2><p>{guide.example}</p></article></section>}
    <section className="shell section"><div className="sectionHead"><div><span className="sectionKicker">{c.related}</span><h2>{c.related}</h2><p>{c.relatedNote}</p></div></div><div className="categoryGrid">{related.map(next=><Link className="categoryCard accent-blue" href={`/${locale}/${next.slug}/`} key={next.toolId}><span className="categoryIcon"><Globe2 size={24}/></span><div><h3>{next.name}</h3><p>{next.intro}</p></div><span>{c.open} <ArrowRight size={14}/></span></Link>)}</div></section>
    <section className="shell faqSection"><span className="sectionKicker">FAQ</span><h2>{c.faq}</h2>{item.faq.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</section>
    {schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>)}
  </main><LocalizedFooter locale={locale}/></>;
}

export function LocalizedPilotHub({locale}:{locale:PilotLocale}){
  const meta=pilotLocaleMeta[locale];const c=copy[locale];const items=localizedPilotTools[locale];
  const schemas=[{"@context":"https://schema.org","@type":"CollectionPage",name:c.hubTitle,url:`https://toolmera.com/${locale}/`,description:c.hubIntro,inLanguage:meta.lang},{"@context":"https://schema.org","@type":"ItemList",numberOfItems:items.length,itemListElement:items.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.name,url:`https://toolmera.com/${locale}/${item.slug}/`}))}];
  return <><LocalizedHeader locale={locale}/><main className="subPage" lang={meta.lang}>
    <section className="shell categoryHero compactHero"><div className="breadcrumbs"><Link href={`/${locale}/`}>{c.home}</Link><ChevronRight/><span>{meta.nativeLabel}</span></div><span className="eyebrow neonText">{c.hubKicker}</span><h1>{c.hubTitle}</h1><p>{c.hubIntro}</p><div className="categoryMeta"><span>{items.length} tools</span><span>{c.free}</span><span>{c.noSignup}</span></div></section>
    <section className="shell section"><div className="sectionHead"><div><span className="sectionKicker">{c.tools}</span><h2>{c.hubTitle}</h2><p>{c.hubNote}</p></div></div><div className="categoryGrid">{items.map(item=><Link className="categoryCard accent-blue" href={`/${locale}/${item.slug}/`} key={item.toolId}><span className="categoryIcon"><Globe2 size={24}/></span><div><h3>{item.name}</h3><p>{item.intro}</p></div><span>{c.open} <ArrowRight size={14}/></span></Link>)}</div></section>
    <section className="shell workflowLinks"><span className="sectionKicker">{c.languages}</span><div><Link href="/en/">English<ArrowRight size={14}/></Link>{(['de','hi','ru'] as PilotLocale[]).filter(code=>code!==locale).map(code=><Link href={`/${code}/`} key={code}>{pilotLocaleMeta[code].nativeLabel}<ArrowRight size={14}/></Link>)}</div></section>
    {schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>)}
  </main><LocalizedFooter locale={locale}/></>;
}
