import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, ChevronRight, Globe2, Grid2X2, ShieldCheck, UserRoundCheck, Zap } from 'lucide-react';
import { Brand } from '@/components/Brand';
import { ThemeToggle } from '@/components/ThemeToggle';
import { CurrencyHubConverter } from '@/components/CurrencyConverter';
import { LocalizedToolExperience, LocalizedUi } from '@/components/LocalizedToolExperience';
import { tools } from '@/data/tools';
import { getLocalizedPilotByToolId, getLocalizedPilotTool, localizedAlternates, localizedPath, localizedPilotTools, pilotLocaleMeta, type PilotLocale, type LocalizedPilotTool } from '@/data/localizedToolPilot';

type LocaleCopy={home:string;tools:string;kicker:string;free:string;private:string;privateNote:string;instant:string;instantNote:string;noSignup:string;noSignupNote:string;why:string;about:string;related:string;relatedNote:string;faq:string;languages:string;open:string;guide:string;example:string;hubKicker:string;hubTitle:string;hubIntro:string;hubNote:string;footerTagline:string;company:string;aboutLink:string;methodology:string;privacy:string;terms:string;nav:{currency:string;calculator:string;images:string;pdf:string;website:string}};

const copy:Record<PilotLocale,LocaleCopy>={
  de:{home:'Startseite',tools:'Tools',kicker:'KOSTENLOSES ONLINE-TOOL',free:'Kostenlos nutzbar',private:'Datenschutzorientiert',privateNote:'Browser-first, wenn technisch möglich',instant:'Schneller Workflow',instantNote:'Ohne Einrichtung direkt starten',noSignup:'Keine Anmeldung',noSignupNote:'Tool öffnen und Aufgabe erledigen',why:'VORTEILE',about:'ÜBER DIESES TOOL',related:'Passende Tools',relatedNote:'Weitere deutschsprachige Tools für denselben Workflow.',faq:'Häufige Fragen',languages:'Dieses Tool in anderen Sprachen',open:'Tool öffnen',guide:'PRAXIS',example:'TYPISCHER EINSATZ',hubKicker:'TOOLMERA / DEUTSCH',hubTitle:'Kostenlose Online-Tools auf Deutsch',hubIntro:'15 ausgewählte Rechner, Konverter, Bild-, PDF- und Website-Tools mit deutschsprachiger Oberfläche, verständlichen Erklärungen und direkter Nutzung im Browser.',hubNote:'Wähle ein Tool und arbeite in derselben Sprachversion weiter. Jede Seite ist auf den konkreten Such- und Nutzungszweck des Tools ausgerichtet.',footerTagline:'Schnelle, praktische Tools für den Alltag.',company:'Unternehmen',aboutLink:'Über Toolmera',methodology:'Methodik',privacy:'Datenschutz',terms:'Bedingungen',nav:{currency:'Währungen',calculator:'Rechner',images:'Bilder',pdf:'PDF',website:'Website'}},
  hi:{home:'होम',tools:'टूल्स',kicker:'मुफ्त ऑनलाइन टूल',free:'मुफ्त उपयोग',private:'प्राइवेसी-केंद्रित',privateNote:'जहाँ संभव हो, प्रोसेसिंग ब्राउज़र में',instant:'तेज़ काम',instantNote:'बिना सेटअप तुरंत शुरू करें',noSignup:'साइन-अप नहीं',noSignupNote:'टूल खोलें और काम पूरा करें',why:'मुख्य फायदे',about:'इस टूल के बारे में',related:'संबंधित टूल्स',relatedNote:'इसी काम से जुड़े दूसरे हिन्दी टूल्स।',faq:'सामान्य सवाल',languages:'यही टूल दूसरी भाषाओं में',open:'टूल खोलें',guide:'व्यावहारिक उपयोग',example:'आम उपयोग',hubKicker:'TOOLMERA / हिन्दी',hubTitle:'हिन्दी में मुफ्त ऑनलाइन टूल्स',hubIntro:'15 चुने हुए कैलकुलेटर, कन्वर्टर, इमेज, PDF और वेबसाइट टूल्स हिन्दी इंटरफ़ेस, साफ़ निर्देश और ब्राउज़र-आधारित वर्कफ़्लो के साथ।',hubNote:'हर पेज एक स्पष्ट काम पर केंद्रित है। टूल चुनें और उसी भाषा में जुड़े हुए दूसरे टूल्स पर जाएँ।',footerTagline:'रोज़मर्रा के काम के लिए तेज़ और उपयोगी टूल्स।',company:'कंपनी',aboutLink:'Toolmera के बारे में',methodology:'मेथडोलॉजी',privacy:'प्राइवेसी',terms:'शर्तें',nav:{currency:'करेंसी',calculator:'कैलकुलेटर',images:'इमेज',pdf:'PDF',website:'वेबसाइट'}},
  ru:{home:'Главная',tools:'Инструменты',kicker:'БЕСПЛАТНЫЙ ОНЛАЙН-ИНСТРУМЕНТ',free:'Бесплатно',private:'Приватный подход',privateNote:'Обработка в браузере, где это возможно',instant:'Быстрый результат',instantNote:'Без настройки и лишних шагов',noSignup:'Без аккаунта',noSignupNote:'Откройте инструмент и выполните задачу',why:'ПРЕИМУЩЕСТВА',about:'ОБ ИНСТРУМЕНТЕ',related:'Связанные инструменты',relatedNote:'Другие русскоязычные инструменты для продолжения работы.',faq:'Частые вопросы',languages:'Этот инструмент на других языках',open:'Открыть',guide:'ПРАКТИКА',example:'ТИПИЧНЫЙ СЦЕНАРИЙ',hubKicker:'TOOLMERA / РУССКИЙ',hubTitle:'Бесплатные онлайн-инструменты на русском',hubIntro:'15 выбранных калькуляторов, конвертеров, инструментов для изображений, PDF и сайтов с русскоязычным интерфейсом и понятными пояснениями.',hubNote:'Каждая страница решает конкретную задачу и связана с другими русскоязычными инструментами того же рабочего процесса.',footerTagline:'Быстрые и практичные инструменты для повседневных задач.',company:'Компания',aboutLink:'О Toolmera',methodology:'Методология',privacy:'Конфиденциальность',terms:'Условия',nav:{currency:'Валюты',calculator:'Калькуляторы',images:'Изображения',pdf:'PDF',website:'Сайты'}},
};

const contexts:Record<PilotLocale,Record<string,string>>={
  de:{currency:'Ideal für Reisen, internationale Rechnungen und schnelle Preisvergleiche mit sichtbarem Kursdatum.',percentage:'Hilfreich für Rabatte, Margen, Preisänderungen und allgemeine Prozentaufgaben mit getrennten Rechenarten.','date-calculator':'Geeignet für Fristen, Projektplanung und Kalenderberechnungen mit echten Monatslängen.','qr-code':'Praktisch für URLs, Kontaktpunkte und Druckmaterial, wenn ein statischer QR-Code als PNG oder SVG benötigt wird.',password:'Für neue Konten oder Zugangsdaten, wenn ein lokal erzeugter zufälliger Wert mit eigener Länge und Zeichenauswahl benötigt wird.','png-webp':'Für transparente Webgrafiken und Screenshots, die als modernes WebP-Asset ausgegeben werden sollen.','jpg-webp':'Für Fotos und Produktbilder, die als webfreundliches WebP mit steuerbarer Qualität benötigt werden.','compress-jpg':'Für große JPEG-Dateien, wenn die Dateigröße sinken soll, ohne das Ausgabeformat zu wechseln.','resize-image':'Für Social Media, Websites und Dokumente, wenn exakte Pixelmaße oder proportionale Skalierung benötigt werden.','merge-pdf':'Für Berichte, Angebote und Anlagen, die in einer kontrollierten Reihenfolge zu einer PDF verbunden werden sollen.','remove-duplicate-lines':'Für Keyword-, URL-, ID- und Exportlisten, in denen wiederholte Zeilen bereinigt werden müssen.',length:'Für technische und alltägliche Umrechnungen zwischen metrischen und imperialen Längeneinheiten.',speed:'Für Straße, Luftfahrt, Schifffahrt und technische Berechnungen zwischen km/h, mph, m/s, ft/s und Knoten.','sitemap-checker':'Für technische SEO-Kontrollen von öffentlichen XML-Sitemaps, URL-Anzahl, lastmod und Sitemap-Indizes.','website-analyzer':'Für einen kompakten Audit öffentlicher SEO-, HTTP-, Crawl-, Security- und Technologiesignale.'},
  hi:{currency:'यात्रा, अंतरराष्ट्रीय भुगतान और अलग-अलग currencies में कीमत तुलना के लिए उपयोगी, साथ में rate date भी दिखाई जाती है।',percentage:'Discount, price change, margin और सामान्य percentage calculations के लिए अलग-अलग calculation modes देता है।','date-calculator':'Deadlines, planning और calendar calculations के लिए, जहाँ असली month lengths महत्वपूर्ण हैं।','qr-code':'URL, text, print material और sharing workflows के लिए static QR code PNG या SVG में बनाने के लिए।',password:'नए accounts और credentials के लिए, जब browser में local random password चाहिए और length/characters चुनने हों।','png-webp':'Transparent web graphics और screenshots को modern WebP output में बदलने के लिए।','jpg-webp':'Photos और product images को web-friendly WebP में बदलने के लिए, quality control के साथ।','compress-jpg':'बड़ी JPEG files का size घटाने के लिए, जबकि output format JPG ही रहता है।','resize-image':'Social media, websites और documents के लिए exact pixel size या proportional resize करने के लिए।','merge-pdf':'Reports, forms और annexures को चुने हुए order में एक PDF document में जोड़ने के लिए।','remove-duplicate-lines':'Keywords, URLs, IDs और exported lists से repeated lines हटाने के लिए।',length:'Metric और imperial length units के बीच रोज़मर्रा और technical conversion के लिए।',speed:'Road, aviation, marine और technical speed conversion के लिए km/h, mph, m/s, ft/s और knots के बीच।','sitemap-checker':'Public XML sitemap की availability, URL count, lastmod और sitemap-index structure जाँचने के लिए।','website-analyzer':'Public URL के SEO, HTTP, crawl, security और technology signals का practical audit करने के लिए।'},
  ru:{currency:'Подходит для поездок, международных платежей и быстрого сравнения цен с понятной датой справочного курса.',percentage:'Полезен для скидок, наценок, изменения цены и других задач, где важно выбрать правильный тип процентного расчёта.','date-calculator':'Для дедлайнов, планирования и календарных расчётов с учётом реальной длины месяцев.','qr-code':'Для ссылок, текстовых данных и печатных материалов, когда нужен статический QR-код в PNG или SVG.',password:'Для новых аккаунтов и доступов, когда нужен локально созданный случайный пароль с выбранной длиной и набором символов.','png-webp':'Для прозрачной веб-графики и скриншотов, которые нужно получить в современном формате WebP.','jpg-webp':'Для фотографий и карточек товаров, которые нужно подготовить в WebP с контролем качества.','compress-jpg':'Для больших JPEG-файлов, когда нужно уменьшить размер без смены формата.', 'resize-image':'Для сайтов, соцсетей и документов, когда нужны точные размеры в пикселях или пропорциональное масштабирование.','merge-pdf':'Для отчётов, договоров и приложений, которые нужно собрать в один PDF в заданном порядке.','remove-duplicate-lines':'Для списков ключевых слов, URL, ID и экспортов, где нужно убрать повторяющиеся строки.',length:'Для бытовых и технических переводов между метрическими и имперскими единицами длины.',speed:'Для дорожных, авиационных, морских и технических расчётов между km/h, mph, m/s, ft/s и узлами.','sitemap-checker':'Для технической проверки публичных XML Sitemap, количества URL, lastmod и sitemap index.','website-analyzer':'Для компактного аудита публичных SEO-, HTTP-, crawl-, security- и technology signals сайта.'},
};

function localeHref(locale:PilotLocale,toolId:string){return localizedPath(locale,toolId)||`/${locale}/`}

function LocalizedHeader({locale}:{locale:PilotLocale}){
  const c=copy[locale];const nav=[[c.tools,`/${locale}/`],[c.nav.currency,localeHref(locale,'currency')],[c.nav.calculator,localeHref(locale,'percentage')],[c.nav.images,localeHref(locale,'compress-jpg')],[c.nav.pdf,localeHref(locale,'merge-pdf')],[c.nav.website,localeHref(locale,'website-analyzer')]];
  return <header className="siteHeader"><div className="shell headerInner"><Brand/><nav className="desktopNav" aria-label={c.tools}>{nav.map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</nav><div className="headerActions"><ThemeToggle/><Link className="allToolsButton" href={`/${locale}/`}><Grid2X2 size={16}/>{c.tools}</Link></div></div></header>;
}

function LocalizedFooter({locale}:{locale:PilotLocale}){
  const c=copy[locale];
  return <footer className="footer"><div className="shell footerGrid footerGridExpanded"><div className="footerBrand"><Brand/><p>{c.footerTagline}</p><span>{c.free} · {c.noSignup}</span></div><div className="footerColumn"><strong>{c.tools}</strong><Link href={`/${locale}/`}>{c.tools}</Link><Link href={localeHref(locale,'currency')}>{c.nav.currency}</Link><Link href={localeHref(locale,'percentage')}>{c.nav.calculator}</Link><Link href={localeHref(locale,'compress-jpg')}>{c.nav.images}</Link><Link href={localeHref(locale,'merge-pdf')}>{c.nav.pdf}</Link><Link href={localeHref(locale,'website-analyzer')}>{c.nav.website}</Link></div><div className="footerColumn"><strong>{c.company}</strong><Link href="/about/">{c.aboutLink}</Link><Link href="/methodology/">{c.methodology}</Link><Link href="/privacy/">{c.privacy}</Link><Link href="/terms/">{c.terms}</Link></div><div className="footerMeta"><span>© {new Date().getFullYear()} Toolmera</span><Link href="/en/">English</Link>{(['de','hi','ru'] as PilotLocale[]).filter(code=>code!==locale).map(code=><Link href={`/${code}/`} key={code}>{pilotLocaleMeta[code].nativeLabel}</Link>)}</div></div></footer>;
}

export function localizedToolMetadata(locale:PilotLocale,slug:string):Metadata{
  const item=getLocalizedPilotTool(locale,slug);if(!item)return{};const meta=pilotLocaleMeta[locale];const canonical=`https://toolmera.com/${locale}/${item.slug}/`;
  return{title:item.title,description:item.description,alternates:{canonical,languages:localizedAlternates(item.toolId,item.englishUrl)},openGraph:{title:item.title,description:item.description,url:canonical,siteName:'Toolmera',type:'website',locale:meta.ogLocale},twitter:{card:'summary',title:item.title,description:item.description},other:{'content-language':meta.lang}};
}

export function localizedHubMetadata(locale:PilotLocale):Metadata{
  const meta=pilotLocaleMeta[locale];const c=copy[locale];const canonical=`https://toolmera.com/${locale}/`;
  return{title:c.hubTitle,description:c.hubIntro,alternates:{canonical,languages:{en:'https://toolmera.com/en/',de:'https://toolmera.com/de/',hi:'https://toolmera.com/hi/',ru:'https://toolmera.com/ru/','x-default':'https://toolmera.com/en/'}},openGraph:{title:c.hubTitle,description:c.hubIntro,url:canonical,siteName:'Toolmera',type:'website',locale:meta.ogLocale},twitter:{card:'summary',title:c.hubTitle,description:c.hubIntro},other:{'content-language':meta.lang}};
}

function languageVersions(toolId:string,englishUrl:string){
  const englishName=toolId==='currency'?'Currency Converter':tools.find(t=>t.id===toolId)?.name||'English';const result:{code:string;label:string;href:string}[]=[{code:'en',label:`English — ${englishName}`,href:englishUrl}];
  for(const locale of ['de','hi','ru'] as PilotLocale[]){const item=getLocalizedPilotByToolId(locale,toolId);if(item)result.push({code:locale,label:`${pilotLocaleMeta[locale].nativeLabel} — ${item.name}`,href:`/${locale}/${item.slug}/`})}
  return result;
}

function LanguageLinks({locale,toolId,englishUrl}:{locale:PilotLocale;toolId:string;englishUrl:string}){
  const c=copy[locale];const current=localizedPath(locale,toolId);
  return <section className="shell workflowLinks" aria-label={c.languages}><span className="sectionKicker">{c.languages}</span><div>{languageVersions(toolId,englishUrl).map(item=><Link href={item.href} key={item.code} aria-current={item.href===current?'page':undefined}>{item.label}<ArrowRight size={14}/></Link>)}</div></section>;
}

function relatedFor(locale:PilotLocale,toolId:string){
  const list=localizedPilotTools[locale];const currentIndex=list.findIndex(item=>item.toolId===toolId);const currentTool=tools.find(t=>t.id===toolId);const circular=currentIndex<0?list:[...list.slice(currentIndex+1),...list.slice(0,currentIndex)];const same=currentTool?circular.filter(item=>tools.find(t=>t.id===item.toolId)?.category===currentTool.category):[];const picks=[...same.slice(0,2),...circular.filter(item=>!same.includes(item))];return [...new Map(picks.map(item=>[item.toolId,item])).values()].slice(0,4);
}

function uniqueSections(locale:PilotLocale,item:LocalizedPilotTool){
  const c=copy[locale];const context=contexts[locale][item.toolId]||item.description;const benefits=item.benefits.join(' · ');const answer=item.faq[0]?.a||item.description;
  if(locale==='de')return[{k:c.guide,title:`${item.name}: sinnvoller Workflow`,body:`${item.intro} ${context}`},{k:c.example,title:`Was du bei ${item.name} direkt prüfen kannst`,body:`Wichtige Funktionen: ${benefits}. ${answer}`}];
  if(locale==='hi')return[{k:c.guide,title:`${item.name} का सही उपयोग`,body:`${item.intro} ${context}`},{k:c.example,title:`${item.name} में क्या देखें`,body:`मुख्य सुविधाएँ: ${benefits}। ${answer}`}];
  return[{k:c.guide,title:`Как использовать ${item.name}`,body:`${item.intro} ${context}`},{k:c.example,title:`Что проверить в ${item.name}`,body:`Ключевые возможности: ${benefits}. ${answer}`}];
}

export function LocalizedPilotToolPage({locale,slug}:{locale:PilotLocale;slug:string}){
  const item=getLocalizedPilotTool(locale,slug);if(!item)return null;const meta=pilotLocaleMeta[locale];const c=copy[locale];const tool=item.toolId==='currency'?null:tools.find(t=>t.id===item.toolId&&!t.country);if(item.toolId!=='currency'&&!tool)return null;const canonical=`https://toolmera.com/${locale}/${item.slug}/`;const related=relatedFor(locale,item.toolId);const sections=uniqueSections(locale,item);
  const schemas:Record<string,unknown>[]=[{"@context":"https://schema.org","@type":"WebApplication",name:item.name,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",url:canonical,description:item.description,inLanguage:meta.lang,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:c.home,item:`https://toolmera.com/${locale}/`},{"@type":"ListItem",position:2,name:meta.nativeLabel,item:`https://toolmera.com/${locale}/`},{"@type":"ListItem",position:3,name:item.name,item:canonical}]}];
  return <><LocalizedHeader locale={locale}/><main className="subPage" lang={meta.lang}><section className="shell toolHero compactToolHero"><div className="breadcrumbs"><Link href={`/${locale}/`}>{c.home}</Link><ChevronRight/><Link href={`/${locale}/`}>{meta.nativeLabel}</Link><ChevronRight/><span>{item.name}</span></div><span className="eyebrow neonText">{c.kicker}</span><h1>{item.name}</h1><p>{item.intro}</p></section><LanguageLinks locale={locale} toolId={item.toolId} englishUrl={item.englishUrl}/><div className="shell">{item.toolId==='currency'?<LocalizedUi locale={locale}><CurrencyHubConverter/></LocalizedUi>:<LocalizedToolExperience tool={tool!} locale={locale}/>}</div><section className="shell toolTrustRow"><div><ShieldCheck/><span><strong>{c.private}</strong><small>{c.privateNote}</small></span></div><div><Zap/><span><strong>{c.instant}</strong><small>{c.instantNote}</small></span></div><div><UserRoundCheck/><span><strong>{c.noSignup}</strong><small>{c.noSignupNote}</small></span></div></section><section className="shell toolContent"><div><span className="sectionKicker">{c.why}</span><h2>{item.name}</h2><ul>{item.benefits.map(x=><li key={x}>{x}</li>)}</ul></div><div><span className="sectionKicker">{c.about}</span><h2>{item.title}</h2><p>{item.description}</p></div></section><section className="shell seoDeepDive">{sections.map(section=><article className="seoArticle" key={section.title}><span className="sectionKicker">{section.k}</span><h2>{section.title}</h2><p>{section.body}</p></article>)}</section><section className="shell section"><div className="sectionHead"><div><span className="sectionKicker">{c.related}</span><h2>{c.related}</h2><p>{c.relatedNote}</p></div></div><div className="categoryGrid">{related.map(next=><Link className="categoryCard accent-blue" href={`/${locale}/${next.slug}/`} key={next.toolId}><span className="categoryIcon"><Globe2 size={24}/></span><div><h3>{next.name}</h3><p>{next.intro}</p></div><span>{c.open} <ArrowRight size={14}/></span></Link>)}</div></section><section className="shell faqSection"><span className="sectionKicker">FAQ</span><h2>{c.faq}</h2>{item.faq.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</section>{schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>)}</main><LocalizedFooter locale={locale}/></>;
}

export function LocalizedPilotHub({locale}:{locale:PilotLocale}){
  const meta=pilotLocaleMeta[locale];const c=copy[locale];const items=localizedPilotTools[locale];const schemas=[{"@context":"https://schema.org","@type":"CollectionPage",name:c.hubTitle,url:`https://toolmera.com/${locale}/`,description:c.hubIntro,inLanguage:meta.lang},{"@context":"https://schema.org","@type":"ItemList",numberOfItems:items.length,itemListElement:items.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.name,url:`https://toolmera.com/${locale}/${item.slug}/`}))}];
  return <><LocalizedHeader locale={locale}/><main className="subPage" lang={meta.lang}><section className="shell categoryHero compactHero"><div className="breadcrumbs"><Link href={`/${locale}/`}>{c.home}</Link><ChevronRight/><span>{meta.nativeLabel}</span></div><span className="eyebrow neonText">{c.hubKicker}</span><h1>{c.hubTitle}</h1><p>{c.hubIntro}</p><div className="categoryMeta"><span>{items.length} tools</span><span>{c.free}</span><span>{c.noSignup}</span></div></section><section className="shell section"><div className="sectionHead"><div><span className="sectionKicker">{c.tools}</span><h2>{c.hubTitle}</h2><p>{c.hubNote}</p></div></div><div className="categoryGrid">{items.map(item=><Link className="categoryCard accent-blue" href={`/${locale}/${item.slug}/`} key={item.toolId}><span className="categoryIcon"><Globe2 size={24}/></span><div><h3>{item.name}</h3><p>{item.intro}</p></div><span>{c.open} <ArrowRight size={14}/></span></Link>)}</div></section><section className="shell workflowLinks"><span className="sectionKicker">{c.languages}</span><div><Link href="/en/">English<ArrowRight size={14}/></Link>{(['de','hi','ru'] as PilotLocale[]).filter(code=>code!==locale).map(code=><Link href={`/${code}/`} key={code}>{pilotLocaleMeta[code].nativeLabel}<ArrowRight size={14}/></Link>)}</div></section>{schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>)}</main><LocalizedFooter locale={locale}/></>;
}
