'use client';

import { useMemo, useState } from 'react';
import { Check, Copy, ShieldCheck } from 'lucide-react';
import type { Tool } from '@/data/tools';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
const globalNumber=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number.isFinite(n)?n:0);
const statNumber=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(Number.isFinite(n)?n:0);
function MetricCard({label,value,suffix=''}:{label:string;value:string|number;suffix?:string}){return <div className="metricCard"><span>{label}</span><strong>{value}{suffix}</strong></div>}

type DateParts={y:number;m:number;d:number};
function parseDateParts(value:string):DateParts|null{const m=value.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return null;const y=+m[1],mo=+m[2],d=+m[3];if(mo<1||mo>12||d<1||d>new Date(Date.UTC(y,mo,0)).getUTCDate())return null;return {y,m:mo,d}}
function dateSerial(p:DateParts){return Math.floor(Date.UTC(p.y,p.m-1,p.d)/86400000)}
function isLeapYear(y:number){return y%4===0&&(y%100!==0||y%400===0)}
function anniversaryFor(start:DateParts,year:number):DateParts{return start.m===2&&start.d===29&&!isLeapYear(year)?{y:year,m:2,d:28}:{y:year,m:start.m,d:start.d}}
function localTodayValue(){const d=new Date(),pad=(v:number)=>String(v).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function calendarAge(start:DateParts,end:DateParts){if(dateSerial(start)>dateSerial(end))return null;let years=end.y-start.y,anchor=anniversaryFor(start,start.y+years);if(dateSerial(anchor)>dateSerial(end)){years--;anchor=anniversaryFor(start,start.y+years)}let months=(end.y-anchor.y)*12+(end.m-anchor.m),days=end.d-anchor.d;if(days<0){months--;let pm=end.m-1,py=end.y;if(pm===0){pm=12;py--}days+=new Date(Date.UTC(py,pm,0)).getUTCDate()}if(months<0)months=0;return {years,months,days}}

function AgeCalculator(){
  const [dob,setDob]=useState('1995-01-01'),[asOf,setAsOf]=useState(localTodayValue);
  const result=useMemo(()=>{const start=parseDateParts(dob),end=parseDateParts(asOf);if(!start||!end)return {error:'Enter valid dates.'} as const;const age=calendarAge(start,end);if(!age)return {error:'Date of birth must be on or before the comparison date.'} as const;const totalDays=dateSerial(end)-dateSerial(start);let next=anniversaryFor(start,end.y);if(dateSerial(next)<dateSerial(end))next=anniversaryFor(start,end.y+1);return {age,totalDays,totalWeeks:Math.floor(totalDays/7),totalHours:totalDays*24,birthdayDays:dateSerial(next)-dateSerial(end)}},[dob,asOf]);
  return <div className="toolUi"><div className="fieldGrid ageFields"><label>Date of birth<input type="date" value={dob} onChange={e=>setDob(e.target.value)}/></label><label>Age as of<input type="date" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label></div>{'error' in result?<div className="toolError">{result.error}</div>:<><div className="metricGrid"><MetricCard label="Years" value={result.age.years}/><MetricCard label="Months" value={result.age.months}/><MetricCard label="Days" value={result.age.days}/><MetricCard label="Total days" value={money(result.totalDays)}/></div><div className="metricGrid compactMetrics"><MetricCard label="Total weeks" value={money(result.totalWeeks)}/><MetricCard label="Total hours" value={money(result.totalHours)}/><MetricCard label="Next birthday" value={result.birthdayDays===0?'Today':`${money(result.birthdayDays)} days`}/></div><div className="toolNote"><ShieldCheck size={15}/><span>Calendar-based calculation. For Feb 29 birthdays, Toolmera treats Feb 28 as the anniversary in non-leap years.</span></div></>}</div>;
}

function BmiCalculator(){
  const [unit,setUnit]=useState<'metric'|'imperial'>('metric'),[weightKg,setWeightKg]=useState(70),[heightCm,setHeightCm]=useState(175);const bmi=heightCm>0?weightKg/((heightCm/100)**2):0,category=bmi<18.5?'Underweight':bmi<25?'Healthy weight':bmi<30?'Overweight':'Obesity',obesityClass=bmi<30?'—':bmi<35?'Class 1':bmi<40?'Class 2':'Class 3',weight=unit==='metric'?weightKg:weightKg*2.2046226218,height=unit==='metric'?heightCm:heightCm/2.54;
  return <div className="toolUi"><div className="calcModeTabs unitTabs"><button className={unit==='metric'?'active':''} onClick={()=>setUnit('metric')}>Metric · kg / cm</button><button className={unit==='imperial'?'active':''} onClick={()=>setUnit('imperial')}>Imperial · lb / in</button></div><div className="fieldGrid calculatorTwoFields"><label>{unit==='metric'?'Weight (kg)':'Weight (lb)'}<input type="number" min="0" step="0.1" value={Number(weight.toFixed(1))} onChange={e=>{const v=+e.target.value;setWeightKg(unit==='metric'?v:v/2.2046226218)}}/></label><label>{unit==='metric'?'Height (cm)':'Height (in)'}<input type="number" min="0" step="0.1" value={Number(height.toFixed(1))} onChange={e=>{const v=+e.target.value;setHeightCm(unit==='metric'?v:v*2.54)}}/></label></div><div className="metricGrid compactMetrics"><MetricCard label="BMI" value={bmi>0?bmi.toFixed(1):'—'}/><MetricCard label="Adult category" value={bmi>0?category:'—'}/><MetricCard label="Obesity class" value={bmi>0?obesityClass:'—'}/></div><div className="toolNote healthNote"><ShieldCheck size={15}/><span>BMI is a general adult screening measure, not a diagnosis. Standard adult categories are not intended for children, teenagers or pregnancy and can be less informative for very muscular or older adults.</span></div></div>;
}

function CompoundInterestCalculator(){
  const [principal,setPrincipal]=useState(10000),[rate,setRate]=useState(6),[years,setYears]=useState(10),[frequency,setFrequency]=useState('monthly'),[monthlyContribution,setMonthlyContribution]=useState(0);
  const result=useMemo(()=>{const periods:Record<string,number>={annual:1,quarterly:4,monthly:12,daily:365},n=periods[frequency]||12,r=Math.max(0,rate)/100,months=Math.max(0,Math.round(years*12)),annualFactor=(1+r/n)**n,monthlyRate=annualFactor**(1/12)-1;let balance=Math.max(0,principal);const rows:{year:number;balance:number;contributions:number;interest:number}[]=[];for(let month=1;month<=months;month++){balance*=1+monthlyRate;balance+=Math.max(0,monthlyContribution);if(month%12===0||month===months){const contributions=Math.max(0,principal)+Math.max(0,monthlyContribution)*month;rows.push({year:month/12,balance,contributions,interest:balance-contributions})}}const contributions=Math.max(0,principal)+Math.max(0,monthlyContribution)*months;return {future:balance,contributions,interest:balance-contributions,rows}},[principal,rate,years,frequency,monthlyContribution]);
  return <div className="toolUi"><div className="fieldGrid compoundFields"><label>Starting amount<input type="number" min="0" value={principal} onChange={e=>setPrincipal(+e.target.value)}/></label><label>Annual rate (%)<input type="number" min="0" step="0.1" value={rate} onChange={e=>setRate(+e.target.value)}/></label><label>Years<input type="number" min="0" step="1" value={years} onChange={e=>setYears(+e.target.value)}/></label><label>Compounding<select value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="annual">Annually</option><option value="quarterly">Quarterly</option><option value="monthly">Monthly</option><option value="daily">Daily</option></select></label><label>Monthly contribution<input type="number" min="0" value={monthlyContribution} onChange={e=>setMonthlyContribution(+e.target.value)}/></label></div><div className="metricGrid compactMetrics"><MetricCard label="Future value" value={globalNumber(result.future)}/><MetricCard label="Total contributed" value={globalNumber(result.contributions)}/><MetricCard label="Interest earned" value={globalNumber(result.interest)}/></div><div className="toolNote"><ShieldCheck size={15}/><span>Monthly contributions are modeled at the end of each month. The selected compounding frequency is converted to its equivalent monthly growth rate for contribution modeling.</span></div>{result.rows.length>0&&<div className="growthTableWrap"><table className="growthTable"><thead><tr><th>Year</th><th>Balance</th><th>Contributed</th><th>Interest</th></tr></thead><tbody>{result.rows.map(row=><tr key={row.year}><td>{Number(row.year.toFixed(2))}</td><td>{globalNumber(row.balance)}</td><td>{globalNumber(row.contributions)}</td><td>{globalNumber(row.interest)}</td></tr>)}</tbody></table></div>}</div>;
}

function LoanCalculator(){
  const [principal,setPrincipal]=useState(25000),[rate,setRate]=useState(7),[term,setTerm]=useState(5),[termUnit,setTermUnit]=useState<'years'|'months'>('years'),[tableView,setTableView]=useState<'yearly'|'monthly'>('yearly');
  const result=useMemo(()=>{const n=termUnit==='years'?Math.round(term*12):Math.round(term);if(principal<=0)return {error:'Enter a loan amount greater than zero.'} as const;if(rate<0)return {error:'Interest rate cannot be negative.'} as const;if(n<=0)return {error:'Loan term must be greater than zero.'} as const;if(n>1200)return {error:'Choose a loan term of 100 years or less.'} as const;const r=rate/12/100,payment=r===0?principal/n:principal*r*(1+r)**n/((1+r)**n-1);let balance=principal;const monthly:{period:number;payment:number;principal:number;interest:number;balance:number}[]=[];for(let i=1;i<=n;i++){const interest=balance*r,principalPaid=i===n?balance:Math.min(balance,payment-interest),actualPayment=principalPaid+interest;balance=Math.max(0,balance-principalPaid);monthly.push({period:i,payment:actualPayment,principal:principalPaid,interest,balance})}const totalRepayment=monthly.reduce((s,r)=>s+r.payment,0),totalInterest=monthly.reduce((s,r)=>s+r.interest,0),yearly=[];for(let i=0;i<monthly.length;i+=12){const chunk=monthly.slice(i,i+12);yearly.push({period:Math.floor(i/12)+1,payment:chunk.reduce((s,r)=>s+r.payment,0),principal:chunk.reduce((s,r)=>s+r.principal,0),interest:chunk.reduce((s,r)=>s+r.interest,0),balance:chunk[chunk.length-1].balance})}return {payment,totalRepayment,totalInterest,monthly,yearly,n}},[principal,rate,term,termUnit]);
  return <div className="toolUi"><div className="fieldGrid batch5Fields"><label>Loan amount<input type="number" min="0" step="100" value={principal} onChange={e=>setPrincipal(+e.target.value)}/></label><label>Annual interest rate (%)<input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(+e.target.value)}/></label><label>Loan term<input type="number" min="1" step="1" value={term} onChange={e=>setTerm(+e.target.value)}/></label><label>Term unit<select value={termUnit} onChange={e=>setTermUnit(e.target.value as 'years'|'months')}><option value="years">Years</option><option value="months">Months</option></select></label></div>{'error' in result?<div className="toolError">{result.error}</div>:<><div className="metricGrid compactMetrics"><MetricCard label="Monthly payment" value={globalNumber(result.payment)}/><MetricCard label="Total interest" value={globalNumber(result.totalInterest)}/><MetricCard label="Total repayment" value={globalNumber(result.totalRepayment)}/></div><div className="toolNote"><ShieldCheck size={15}/><span>Fixed-rate amortization model. The calculator excludes fees, insurance, taxes, prepayments and variable-rate changes.</span></div><div className="tableToolbar"><div><strong>Amortization schedule</strong><small>{result.n} monthly payments</small></div><div className="calcModeTabs tableTabs"><button className={tableView==='yearly'?'active':''} onClick={()=>setTableView('yearly')}>Yearly</button><button className={tableView==='monthly'?'active':''} onClick={()=>setTableView('monthly')}>Monthly</button></div></div><div className="growthTableWrap"><table className="growthTable"><thead><tr><th>{tableView==='yearly'?'Year':'Month'}</th><th>Payment</th><th>Principal</th><th>Interest</th><th>Balance</th></tr></thead><tbody>{(tableView==='yearly'?result.yearly:result.monthly).map(row=><tr key={row.period}><td>{row.period}</td><td>{globalNumber(row.payment)}</td><td>{globalNumber(row.principal)}</td><td>{globalNumber(row.interest)}</td><td>{globalNumber(row.balance)}</td></tr>)}</tbody></table></div></>}</div>;
}

function RoiCalculator(){
  const [invested,setInvested]=useState(10000),[returned,setReturned]=useState(13500),[years,setYears]=useState(3);const result=useMemo(()=>{if(invested<=0)return {error:'Initial investment must be greater than zero.'} as const;const net=returned-invested,roi=net/invested*100,annualized=years>0&&returned>0?((returned/invested)**(1/years)-1)*100:null;return {net,roi,annualized}},[invested,returned,years]);
  return <div className="toolUi"><div className="fieldGrid"><label>Amount invested<input type="number" step="100" value={invested} onChange={e=>setInvested(+e.target.value)}/></label><label>Amount returned<input type="number" step="100" value={returned} onChange={e=>setReturned(+e.target.value)}/></label><label>Duration (years, optional)<input type="number" min="0" step="0.1" value={years} onChange={e=>setYears(+e.target.value)}/></label></div>{'error' in result?<div className="toolError">{result.error}</div>:<><div className="metricGrid compactMetrics"><MetricCard label="Total ROI" value={result.roi.toFixed(2)+'%'}/><MetricCard label={result.net>=0?'Net gain':'Net loss'} value={globalNumber(Math.abs(result.net))}/><MetricCard label="Annualized ROI" value={result.annualized===null?'—':result.annualized.toFixed(2)+'%'}/></div><div className="formulaNote"><span>Formula</span><code>ROI = (Returned − Invested) ÷ Invested × 100</code></div><div className="toolNote"><ShieldCheck size={15}/><span>Annualized ROI is shown only when duration is above zero and the ending value is positive. This is a mathematical scenario, not investment advice.</span></div></>}</div>;
}

function DiscountCalculator(){
  const [mode,setMode]=useState<'percent'|'fixed'>('percent'),[price,setPrice]=useState(100),[primary,setPrimary]=useState(20),[secondary,setSecondary]=useState(10);const result=useMemo(()=>{if(price<=0)return {error:'Enter an original price greater than zero.'} as const;const firstSavings=mode==='percent'?price*Math.min(100,Math.max(0,primary))/100:Math.min(price,Math.max(0,primary)),afterFirst=Math.max(0,price-firstSavings),secondSavings=afterFirst*Math.min(100,Math.max(0,secondary))/100,savings=Math.min(price,firstSavings+secondSavings),finalPrice=Math.max(0,price-savings);return {savings,finalPrice,effective:savings/price*100}},[mode,price,primary,secondary]);
  return <div className="toolUi"><div className="calcModeTabs unitTabs"><button className={mode==='percent'?'active':''} onClick={()=>setMode('percent')}>Percentage off</button><button className={mode==='fixed'?'active':''} onClick={()=>setMode('fixed')}>Fixed amount off</button></div><div className="fieldGrid"><label>Original price<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(+e.target.value)}/></label><label>{mode==='percent'?'Primary discount (%)':'Fixed discount amount'}<input type="number" min="0" step="0.01" value={primary} onChange={e=>setPrimary(+e.target.value)}/></label><label>Extra discount (%)<input type="number" min="0" max="100" step="0.01" value={secondary} onChange={e=>setSecondary(+e.target.value)}/></label></div>{mode==='percent'&&<div className="quickPills">{[10,15,20,25,50].map(v=><button key={v} onClick={()=>setPrimary(v)}>{v}% off</button>)}</div>}{'error' in result?<div className="toolError">{result.error}</div>:<><div className="metricGrid compactMetrics"><MetricCard label="Final price" value={globalNumber(result.finalPrice)}/><MetricCard label="Total savings" value={globalNumber(result.savings)}/><MetricCard label="Effective discount" value={result.effective.toFixed(2)+'%'}/></div><div className="toolNote"><ShieldCheck size={15}/><span>The extra discount is applied sequentially to the already-reduced price. For example, 20% off plus 10% off is an effective 28% discount, not 30%.</span></div></>}</div>;
}

function SimpleInterestCalculator(){
  const [principal,setPrincipal]=useState(10000),[rate,setRate]=useState(5),[time,setTime]=useState(2),[unit,setUnit]=useState<'years'|'months'|'days'>('years'),[dayBasis,setDayBasis]=useState<365|360>(365);const result=useMemo(()=>{if(principal<=0)return {error:'Principal must be greater than zero.'} as const;if(rate<0)return {error:'Interest rate cannot be negative.'} as const;if(time<=0)return {error:'Time period must be greater than zero.'} as const;const years=unit==='years'?time:unit==='months'?time/12:time/dayBasis,interest=principal*(rate/100)*years,total=principal+interest,annualInterest=principal*(rate/100);return {interest,total,monthlyInterest:annualInterest/12}},[principal,rate,time,unit,dayBasis]);
  return <div className="toolUi"><div className="fieldGrid batch5Fields"><label>Principal amount<input type="number" min="0" step="100" value={principal} onChange={e=>setPrincipal(+e.target.value)}/></label><label>Annual interest rate (%)<input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(+e.target.value)}/></label><label>Time period<input type="number" min="0" step="0.01" value={time} onChange={e=>setTime(+e.target.value)}/></label><label>Time unit<select value={unit} onChange={e=>setUnit(e.target.value as 'years'|'months'|'days')}><option value="years">Years</option><option value="months">Months</option><option value="days">Days</option></select></label>{unit==='days'&&<label>Day-count basis<select value={dayBasis} onChange={e=>setDayBasis(Number(e.target.value) as 365|360)}><option value={365}>365-day year</option><option value={360}>360-day banking year</option></select></label>}</div>{'error' in result?<div className="toolError">{result.error}</div>:<><div className="metricGrid compactMetrics"><MetricCard label="Simple interest" value={globalNumber(result.interest)}/><MetricCard label="Total amount" value={globalNumber(result.total)}/><MetricCard label="Interest / month" value={globalNumber(result.monthlyInterest)}/></div><div className="formulaNote"><span>Formula</span><code>I = P × r × t</code></div><div className="toolNote"><ShieldCheck size={15}/><span>Simple interest is calculated only on the original principal. Day calculations use the selected 365-day or 360-day basis.</span></div></>}</div>;
}

function daysInMonth(year:number,month:number){return new Date(Date.UTC(year,month,0)).getUTCDate()}
function addYearsClamped(p:DateParts,years:number):DateParts{const y=p.y+years;return {y,m:p.m,d:Math.min(p.d,daysInMonth(y,p.m))}}
function addMonthsClamped(p:DateParts,months:number):DateParts{const index=(p.m-1)+months,y=p.y+Math.floor(index/12),m=((index%12)+12)%12+1;return {y,m,d:Math.min(p.d,daysInMonth(y,m))}}
function datePartsFromSerial(serial:number):DateParts{const d=new Date(serial*86400000);return {y:d.getUTCFullYear(),m:d.getUTCMonth()+1,d:d.getUTCDate()}}
function calendarDifference(start:DateParts,end:DateParts){let years=end.y-start.y,yearAnchor=addYearsClamped(start,years);if(dateSerial(yearAnchor)>dateSerial(end)){years--;yearAnchor=addYearsClamped(start,years)}let months=(end.y-yearAnchor.y)*12+(end.m-yearAnchor.m),monthAnchor=addMonthsClamped(yearAnchor,months);if(dateSerial(monthAnchor)>dateSerial(end)){months--;monthAnchor=addMonthsClamped(yearAnchor,months)}return {years,months,days:dateSerial(end)-dateSerial(monthAnchor)}}
function businessDaysBetween(startSerial:number,endExclusive:number){let count=0;for(let s=startSerial;s<endExclusive;s++){const day=new Date(s*86400000).getUTCDay();if(day!==0&&day!==6)count++}return count}

function DateDifferenceCalculator(){
  const [startValue,setStartValue]=useState('2026-01-01'),[endValue,setEndValue]=useState(localTodayValue),[includeEnd,setIncludeEnd]=useState(false);const result=useMemo(()=>{const start=parseDateParts(startValue),end=parseDateParts(endValue);if(!start||!end)return {error:'Enter two valid dates.'} as const;const startSerial=dateSerial(start),endSerial=dateSerial(end);if(endSerial<startSerial)return {error:'End date must be on or after the start date.'} as const;const endExclusive=endSerial+(includeEnd?1:0),duration=calendarDifference(start,datePartsFromSerial(endExclusive)),totalDays=endExclusive-startSerial;return {duration,totalDays,fullWeeks:Math.floor(totalDays/7),remainingDays:totalDays%7,businessDays:businessDaysBetween(startSerial,endExclusive),hours:totalDays*24}},[startValue,endValue,includeEnd]);
  return <div className="toolUi"><div className="fieldGrid calculatorTwoFields"><label>Start date<input type="date" value={startValue} onChange={e=>setStartValue(e.target.value)}/></label><label>End date<input type="date" value={endValue} onChange={e=>setEndValue(e.target.value)}/></label></div><label className="checkControl"><input type="checkbox" checked={includeEnd} onChange={e=>setIncludeEnd(e.target.checked)}/><span>Include end date (+1 day)</span></label>{'error' in result?<div className="toolError">{result.error}</div>:<><div className="durationHero"><strong>{result.duration.years} years, {result.duration.months} months, {result.duration.days} days</strong><span>Calendar duration</span></div><div className="metricGrid dateMetricGrid"><MetricCard label="Total days" value={globalNumber(result.totalDays)}/><MetricCard label="Weeks + days" value={result.fullWeeks+'w '+result.remainingDays+'d'}/><MetricCard label="Business days" value={globalNumber(result.businessDays)}/><MetricCard label="Total hours" value={globalNumber(result.hours)}/></div><div className="toolNote"><ShieldCheck size={15}/><span>Business days exclude Saturdays and Sundays only. Public holidays vary by country and are not removed automatically.</span></div></>}</div>;
}

type AverageResult=
  | {kind:'empty'}
  | {kind:'error';error:string}
  | {kind:'ok';count:number;sum:number;mean:number;median:number;modes:number[];min:number;max:number;range:number};

function AverageCalculator(){
  const [text,setText]=useState('12, 18, 18, 24, 30'),[copied,setCopied]=useState(false);
  const result=useMemo<AverageResult>(()=>{
    const trimmed=text.trim();if(!trimmed)return {kind:'empty'};
    const values=trimmed.split(/[\s,]+/).filter(Boolean).map(Number);if(values.some(v=>!Number.isFinite(v)))return {kind:'error',error:'Enter numbers separated by spaces, commas or line breaks.'};
    const sorted=[...values].sort((a,b)=>a-b),count=values.length,sum=values.reduce((s,v)=>s+v,0),mean=sum/count,median=count%2?sorted[(count-1)/2]:(sorted[count/2-1]+sorted[count/2])/2,freq=new Map<number,number>();
    values.forEach(v=>freq.set(v,(freq.get(v)||0)+1));const maxFreq=Math.max(...freq.values()),modes=maxFreq<=1?[]:[...freq.entries()].filter(([,f])=>f===maxFreq).map(([v])=>v).sort((a,b)=>a-b),min=sorted[0],max=sorted[sorted.length-1];
    return {kind:'ok',count,sum,mean,median,modes,min,max,range:max-min};
  },[text]);
  async function copySummary(){if(result.kind!=='ok')return;await navigator.clipboard.writeText(['Mean: '+statNumber(result.mean),'Median: '+statNumber(result.median),'Mode: '+(result.modes.length?result.modes.map(statNumber).join(', '):'No mode'),'Range: '+statNumber(result.range),'Count: '+result.count,'Sum: '+statNumber(result.sum),'Min: '+statNumber(result.min),'Max: '+statNumber(result.max)].join('\n'));setCopied(true);window.setTimeout(()=>setCopied(false),1400)}
  return <div className="toolUi"><textarea className="textArea statsInput" value={text} onChange={e=>{setText(e.target.value);setCopied(false)}} placeholder="Enter numbers separated by commas, spaces or line breaks…"/>{result.kind==='error'?<div className="toolError">{result.error}</div>:result.kind==='empty'?<div className="toolNote"><ShieldCheck size={15}/><span>Enter at least one number to calculate the statistical summary.</span></div>:<><div className="metricGrid statMetricGrid"><MetricCard label="Mean" value={statNumber(result.mean)}/><MetricCard label="Median" value={statNumber(result.median)}/><MetricCard label="Mode" value={result.modes.length?result.modes.map(statNumber).join(', '):'No mode'}/><MetricCard label="Range" value={statNumber(result.range)}/><MetricCard label="Count" value={result.count}/><MetricCard label="Sum" value={statNumber(result.sum)}/><MetricCard label="Minimum" value={statNumber(result.min)}/><MetricCard label="Maximum" value={statNumber(result.max)}/></div><button className="secondaryButton summaryCopy" onClick={copySummary}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy statistical summary'}</button></>}</div>;
}

export function GeneralCalculatorsExperience({tool}:{tool:Tool}){
  let ui=null;
  if(tool.kind==='age')ui=<AgeCalculator/>;
  else if(tool.kind==='bmi')ui=<BmiCalculator/>;
  else if(tool.kind==='interest')ui=<CompoundInterestCalculator/>;
  else if(tool.kind==='loan')ui=<LoanCalculator/>;
  else if(tool.kind==='roi')ui=<RoiCalculator/>;
  else if(tool.kind==='discount')ui=<DiscountCalculator/>;
  else if(tool.kind==='simple-interest')ui=<SimpleInterestCalculator/>;
  else if(tool.kind==='date-difference')ui=<DateDifferenceCalculator/>;
  else if(tool.kind==='average')ui=<AverageCalculator/>;
  return <section className={`toolExperience accent-${tool.accent}`}><div className="experienceTop"><div><span className="eyebrow">TOOLMERA / {tool.categoryLabel.toUpperCase()}</span><div className="experienceTitle">{tool.name}</div></div><span className="privatePill"><ShieldCheck size={15}/> Browser-first processing</span></div>{ui}</section>;
}
