'use client';

import { PointerEvent, useEffect, useRef, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import type { Tool } from '@/data/tools';
import { BatchFileList, DownloadResult, DownloadResults, FileDrop, MAX_BATCH_FILES, Result, imageToCanvas, mergeBatchFiles } from './FileToolPrimitives';

function ImageConvert({tool}:{tool:Tool}){
  const [quality,setQuality]=useState(82),[results,setResults]=useState<Result[]>([]),[busy,setBusy]=useState(false),[busyLabel,setBusyLabel]=useState('Processing…'),[files,setFiles]=useState<File[]>([]),[background,setBackground]=useState('#ffffff'),[error,setError]=useState('');
  function choose(incoming:File[]){const merged=mergeBatchFiles(files,incoming);setFiles(merged.files);setResults([]);setError(merged.overflow?'Maximum 4 files per batch. Remove one to add another.':'')}
  function remove(index:number){setFiles(files.filter((_,i)=>i!==index));setResults([]);setError('')}
  const outputName=tool.outputFormat?.split('/')[1].replace('jpeg','JPG').toUpperCase()||'IMAGE';
  async function run(){if(!files.length)return;setBusy(true);setResults([]);setError('');const output:Result[]=[];try{for(let i=0;i<files.length;i++){const file=files[i];setBusyLabel(`Converting ${i+1} of ${files.length} to ${outputName}…`);const {bitmap,canvas,ctx}=await imageToCanvas(file);if(tool.outputFormat==='image/jpeg'){ctx.fillStyle=background;ctx.fillRect(0,0,canvas.width,canvas.height)}ctx.drawImage(bitmap,0,0);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Conversion failed.')),tool.outputFormat,quality/100));const ext=tool.outputFormat?.split('/')[1].replace('jpeg','jpg')||'image';output.push({url:URL.createObjectURL(blob),name:file.name.replace(/\.[^.]+$/,'')+'.'+ext,before:file.size,after:blob.size});bitmap.close()}setResults(output)}catch(e){setError(e instanceof Error?e.message:'Could not convert one of these images.')}finally{setBusy(false)}}
  return <div className="toolUi"><FileDrop accept={tool.inputFormat||'image/*'} multiple onChange={choose} label={'Choose '+tool.name.split(' to ')[0]+' files'} files={files} busy={busy} busyLabel={busyLabel} maxFiles={MAX_BATCH_FILES}/>{!busy&&<BatchFileList files={files} onRemove={remove}/>} {files.length>0&&!busy&&<><div className="controlRow"><label>Quality <b>{quality}%</b></label><input type="range" min="35" max="100" value={quality} onChange={e=>setQuality(+e.target.value)}/>{tool.outputFormat==='image/jpeg'&&<label className="colorControl">Background <input type="color" value={background} onChange={e=>setBackground(e.target.value)}/><b>{background.toUpperCase()}</b></label>}</div><button className="primaryButton wide filePrimaryAction" onClick={run}>Convert {files.length} file{files.length===1?'':'s'} to {outputName}</button></>}{error&&<div className="toolError">{error}</div>}<DownloadResults results={results}/></div>;
}

function ImageCompress(){
  const [quality,setQuality]=useState(75),[files,setFiles]=useState<File[]>([]),[results,setResults]=useState<Result[]>([]),[busy,setBusy]=useState(false),[busyLabel,setBusyLabel]=useState('Compressing…'),[error,setError]=useState('');
  function choose(incoming:File[]){const merged=mergeBatchFiles(files,incoming);setFiles(merged.files);setResults([]);setError(merged.overflow?'Maximum 4 files per batch. Remove one to add another.':'')}
  function remove(index:number){setFiles(files.filter((_,i)=>i!==index));setResults([]);setError('')}
  async function run(){if(!files.length)return;setBusy(true);setResults([]);setError('');const output:Result[]=[];try{for(let i=0;i<files.length;i++){const file=files[i];setBusyLabel(`Compressing ${i+1} of ${files.length}…`);const {bitmap,canvas,ctx}=await imageToCanvas(file);ctx.drawImage(bitmap,0,0);const type=file.type==='image/png'?'image/webp':(file.type||'image/jpeg');const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Compression failed.')),type,quality/100));output.push({url:URL.createObjectURL(blob),name:file.name.replace(/\.[^.]+$/,'')+'-compressed.'+type.split('/')[1].replace('jpeg','jpg'),before:file.size,after:blob.size});bitmap.close()}setResults(output)}catch(e){setError(e instanceof Error?e.message:'Could not compress one of these images.')}finally{setBusy(false)}}
  const hasPng=files.some(file=>file.type==='image/png');
  return <div className="toolUi"><FileDrop accept="image/png,image/jpeg,image/webp" multiple onChange={choose} files={files} busy={busy} busyLabel={busyLabel} maxFiles={MAX_BATCH_FILES}/>{!busy&&<BatchFileList files={files} onRemove={remove}/>} {hasPng&&<div className="toolNote"><ShieldCheck size={15}/><span>PNG input is exported as WebP in the current general compressor for stronger browser-side size reduction.</span></div>}{files.length>0&&!busy&&<><div className="controlRow"><label>Compression quality <b>{quality}%</b></label><input type="range" min="30" max="95" value={quality} onChange={e=>setQuality(+e.target.value)}/></div><button className="primaryButton wide filePrimaryAction" onClick={run}>Compress {files.length} file{files.length===1?'':'s'}</button></>}{error&&<div className="toolError">{error}</div>}<DownloadResults results={results}/></div>;
}

function ImageResize(){
  const [file,setFile]=useState<File|null>(null),[width,setWidth]=useState(1200),[height,setHeight]=useState(800),[ratio,setRatio]=useState(1.5),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[busyLabel,setBusyLabel]=useState('Reading image…'),[error,setError]=useState('');
  async function select(files:File[]){if(!files[0])return;const f=files[0];setFile(f);setResult(null);setError('');setBusyLabel('Reading image…');setBusy(true);try{const b=await createImageBitmap(f);setWidth(b.width);setHeight(b.height);setRatio(b.width/b.height);b.close()}catch(e){setError(e instanceof Error?e.message:'Could not read this image.');setFile(null)}finally{setBusy(false)}}
  async function resize(){if(!file)return;setBusyLabel('Resizing image…');setBusy(true);setResult(null);setError('');try{const b=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d')!.drawImage(b,0,0,width,height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(x=>x?resolve(x):reject(new Error('Resize failed.')),file.type||'image/png',.9));setResult({url:URL.createObjectURL(blob),name:file.name.replace(/\.[^.]+$/,'')+'-'+width+'x'+height+'.'+(file.type||'image/png').split('/')[1].replace('jpeg','jpg'),before:file.size,after:blob.size});b.close()}catch(e){setError(e instanceof Error?e.message:'Could not resize this image.')}finally{setBusy(false)}}
  return <div className="toolUi"><FileDrop accept="image/*" onChange={select} files={file?[file]:[]} busy={busy} busyLabel={busyLabel}/>{file&&!busy&&<><div className="fieldGrid fileSettingsGrid"><label>Width<input type="number" value={width} onChange={e=>{const w=+e.target.value;setWidth(w);setHeight(Math.round(w/ratio))}}/></label><label>Height<input type="number" value={height} onChange={e=>{const h=+e.target.value;setHeight(h);setWidth(Math.round(h*ratio))}}/></label></div><button className="primaryButton wide filePrimaryAction" onClick={resize}>Resize image</button></>}{error&&<div className="toolError">{error}</div>}{result&&<DownloadResult result={result}/>}</div>;
}

function ImageCompressJpg(){
  const [quality,setQuality]=useState(80),[files,setFiles]=useState<File[]>([]),[results,setResults]=useState<Result[]>([]),[busy,setBusy]=useState(false),[busyLabel,setBusyLabel]=useState('Compressing JPG…'),[error,setError]=useState('');
  function choose(incoming:File[]){const valid=incoming.filter(f=>f.type==='image/jpeg'||/\.jpe?g$/i.test(f.name));const merged=mergeBatchFiles(files,valid);setFiles(merged.files);setResults([]);setError(valid.length!==incoming.length?'Only JPG/JPEG files were added.':merged.overflow?'Maximum 4 files per batch. Remove one to add another.':'')}
  function remove(index:number){setFiles(files.filter((_,i)=>i!==index));setResults([]);setError('')}
  async function run(){if(!files.length)return;setBusy(true);setResults([]);setError('');const output:Result[]=[];try{for(let i=0;i<files.length;i++){const file=files[i];setBusyLabel(`Compressing JPG ${i+1} of ${files.length}…`);const {bitmap,canvas,ctx}=await imageToCanvas(file);ctx.drawImage(bitmap,0,0);const encoded=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('JPEG compression failed.')),'image/jpeg',quality/100));const out=encoded.size<file.size?encoded:file;output.push({url:URL.createObjectURL(out),name:file.name.replace(/\.[^.]+$/,'')+'-compressed.jpg',before:file.size,after:out.size});bitmap.close()}setResults(output)}catch(e){setError(e instanceof Error?e.message:'Could not compress one of these JPG files.')}finally{setBusy(false)}}
  return <div className="toolUi"><FileDrop accept="image/jpeg,.jpg,.jpeg" multiple onChange={choose} label="Choose JPG files" files={files} busy={busy} busyLabel={busyLabel} maxFiles={MAX_BATCH_FILES}/>{!busy&&<BatchFileList files={files} onRemove={remove}/>} {files.length>0&&!busy&&<><div className="controlRow"><label>JPEG quality <b>{quality}%</b></label><input type="range" min="30" max="95" value={quality} onChange={e=>setQuality(+e.target.value)}/></div><button className="primaryButton wide filePrimaryAction" onClick={run}>Compress {files.length} JPG{files.length===1?'':'s'}</button></>}<div className="toolNote"><ShieldCheck size={15}/><span>If re-encoding would make a file larger, Toolmera keeps the original JPG bytes for that file instead.</span></div>{error&&<div className="toolError">{error}</div>}<DownloadResults results={results}/></div>;
}

function ImageCompressPng(){
  const [colors,setColors]=useState(256),[files,setFiles]=useState<File[]>([]),[results,setResults]=useState<Result[]>([]),[busy,setBusy]=useState(false),[busyLabel,setBusyLabel]=useState('Optimizing PNG…'),[error,setError]=useState('');
  function choose(incoming:File[]){const valid=incoming.filter(f=>f.type==='image/png'||/\.png$/i.test(f.name));const merged=mergeBatchFiles(files,valid);setFiles(merged.files);setResults([]);setError(valid.length!==incoming.length?'Only PNG files were added.':merged.overflow?'Maximum 4 files per batch. Remove one to add another.':'')}
  function remove(index:number){setFiles(files.filter((_,i)=>i!==index));setResults([]);setError('')}
  async function run(){if(!files.length)return;setBusy(true);setResults([]);setError('');const output:Result[]=[];try{const mod=await import('@upng/upng-js');const UPNG=(mod.default||mod) as unknown as {encode:(frames:ArrayBuffer[],w:number,h:number,cnum:number)=>ArrayBuffer};for(let i=0;i<files.length;i++){const file=files[i];setBusyLabel(`Optimizing PNG ${i+1} of ${files.length}…`);const {bitmap,canvas,ctx}=await imageToCanvas(file);ctx.drawImage(bitmap,0,0);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);const rgba=pixels.data.buffer.slice(pixels.data.byteOffset,pixels.data.byteOffset+pixels.data.byteLength) as ArrayBuffer;const encoded=UPNG.encode([rgba],canvas.width,canvas.height,colors),blob=new Blob([encoded],{type:'image/png'});output.push({url:URL.createObjectURL(blob),name:file.name.replace(/\.[^.]+$/,'')+'-compressed.png',before:file.size,after:blob.size});bitmap.close()}setResults(output)}catch(e){setError(e instanceof Error?e.message:'Could not compress one of these PNG files.')}finally{setBusy(false)}}
  return <div className="toolUi"><FileDrop accept="image/png,.png" multiple onChange={choose} label="Choose PNG files" files={files} busy={busy} busyLabel={busyLabel} maxFiles={MAX_BATCH_FILES}/>{!busy&&<BatchFileList files={files} onRemove={remove}/>} {files.length>0&&!busy&&<><div className="calcModeTabs unitTabs">{[256,128,64].map(v=><button key={v} className={colors===v?'active':''} onClick={()=>setColors(v)}>{v} colors</button>)}</div><button className="primaryButton wide filePrimaryAction" onClick={run}>Compress {files.length} PNG{files.length===1?'':'s'}</button></>}<div className="toolNote"><ShieldCheck size={15}/><span>PNG stays PNG. Palette quantization can reduce color precision, so compare each result before replacing an original asset.</span></div>{error&&<div className="toolError">{error}</div>}<DownloadResults results={results}/></div>;
}

function HeicConverter(){
  const [files,setFiles]=useState<File[]>([]),[format,setFormat]=useState<'jpg'|'png'>('jpg'),[quality,setQuality]=useState(85),[results,setResults]=useState<Result[]>([]),[busy,setBusy]=useState(false),[busyLabel,setBusyLabel]=useState('Converting HEIC…'),[error,setError]=useState('');
  function choose(incoming:File[]){const valid=incoming.filter(f=>/\.(heic|heif)$/i.test(f.name)||['image/heic','image/heif'].includes(f.type));const merged=mergeBatchFiles(files,valid);setFiles(merged.files);setResults([]);setError(valid.length!==incoming.length?'Only HEIC/HEIF files were added.':merged.overflow?'Maximum 4 files per batch. Remove one to add another.':'')}
  function remove(index:number){setFiles(files.filter((_,i)=>i!==index));setResults([]);setError('')}
  async function run(){if(!files.length)return;setBusy(true);setResults([]);setError('');const output:Result[]=[];try{const mod=await import('heic2any'),convert=mod.default;for(let i=0;i<files.length;i++){const file=files[i];setBusyLabel(`Converting HEIC ${i+1} of ${files.length} to ${format.toUpperCase()}…`);const converted=await convert({blob:file,toType:format==='jpg'?'image/jpeg':'image/png',quality:quality/100});const blob=Array.isArray(converted)?converted[0]:converted;if(!blob)throw new Error('A HEIC file did not produce a usable image.');output.push({url:URL.createObjectURL(blob),name:file.name.replace(/\.[^.]+$/,'')+'.'+format,before:file.size,after:blob.size})}setResults(output)}catch(e){setError(e instanceof Error?e.message:'Could not decode one of these HEIC files.')}finally{setBusy(false)}}
  return <div className="toolUi"><FileDrop accept=".heic,.heif,image/heic,image/heif" multiple onChange={choose} label="Choose HEIC / HEIF photos" files={files} busy={busy} busyLabel={busyLabel} maxFiles={MAX_BATCH_FILES}/>{!busy&&<BatchFileList files={files} onRemove={remove}/>} {files.length>0&&!busy&&<><div className="calcModeTabs unitTabs"><button className={format==='jpg'?'active':''} onClick={()=>setFormat('jpg')}>JPG output</button><button className={format==='png'?'active':''} onClick={()=>setFormat('png')}>PNG output</button></div>{format==='jpg'&&<div className="controlRow"><label>JPG quality <b>{quality}%</b></label><input type="range" min="40" max="100" value={quality} onChange={e=>setQuality(+e.target.value)}/></div>}<button className="primaryButton wide filePrimaryAction" onClick={run}>Convert {files.length} file{files.length===1?'':'s'} to {format.toUpperCase()}</button></>}<div className="toolNote"><ShieldCheck size={15}/><span>The converted files are fresh images and do not preserve the original HEIC metadata. Very large phone photos can use substantial browser memory.</span></div>{error&&<div className="toolError">{error}</div>}<DownloadResults results={results}/></div>;
}

type CropRect={x:number;y:number;w:number;h:number};
function CropImage(){
  const bitmapRef=useRef<ImageBitmap|null>(null),canvasRef=useRef<HTMLCanvasElement|null>(null),dragStart=useRef<{x:number;y:number}|null>(null);
  const [file,setFile]=useState<File|null>(null),[crop,setCrop]=useState<CropRect>({x:0,y:0,w:1,h:1}),[ratio,setRatio]=useState<'free'|'1:1'|'4:3'|'16:9'|'9:16'>('free'),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[busyLabel,setBusyLabel]=useState('Reading image…');
  function redraw(){const bitmap=bitmapRef.current,canvas=canvasRef.current;if(!bitmap||!canvas)return;canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext('2d')!;ctx.drawImage(bitmap,0,0);ctx.fillStyle='rgba(2,5,8,.58)';ctx.fillRect(0,0,canvas.width,canvas.height);if(crop.w>0&&crop.h>0){ctx.drawImage(bitmap,crop.x,crop.y,crop.w,crop.h,crop.x,crop.y,crop.w,crop.h);ctx.strokeStyle='#4cAAff';ctx.lineWidth=Math.max(2,Math.round(canvas.width/500));ctx.strokeRect(crop.x,crop.y,crop.w,crop.h)}}
  useEffect(redraw,[crop,file]);
  async function choose(files:File[]){if(!files[0])return;const input=files[0];setFile(input);setError('');setResult(null);setBusyLabel('Reading image…');setBusy(true);try{if(!['image/jpeg','image/png','image/webp'].includes(input.type))throw new Error('Choose a JPG, PNG or WebP image.');bitmapRef.current?.close();const bitmap=await createImageBitmap(input);bitmapRef.current=bitmap;setCrop({x:0,y:0,w:bitmap.width,h:bitmap.height})}catch(e){setError(e instanceof Error?e.message:'Could not open this image.');setFile(null)}finally{setBusy(false)}}
  function canvasPoint(e:PointerEvent<HTMLCanvasElement>){const canvas=canvasRef.current!,box=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(e.clientX-box.left)*canvas.width/box.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-box.top)*canvas.height/box.height))}}
  function ratioValue(){return ratio==='1:1'?1:ratio==='4:3'?4/3:ratio==='16:9'?16/9:ratio==='9:16'?9/16:null}
  function pointerDown(e:PointerEvent<HTMLCanvasElement>){if(!file)return;dragStart.current=canvasPoint(e);e.currentTarget.setPointerCapture(e.pointerId)}
  function pointerMove(e:PointerEvent<HTMLCanvasElement>){if(!dragStart.current||!bitmapRef.current)return;const p=canvasPoint(e),s=dragStart.current;let dx=p.x-s.x,dy=p.y-s.y;const rv=ratioValue();if(rv){const sx=dx<0?-1:1,sy=dy<0?-1:1;let w=Math.abs(dx),h=Math.abs(dy);if(w/Math.max(1,h)>rv)w=h*rv;else h=w/rv;dx=w*sx;dy=h*sy}const x=Math.max(0,Math.min(s.x,s.x+dx)),y=Math.max(0,Math.min(s.y,s.y+dy)),w=Math.min(bitmapRef.current.width-x,Math.abs(dx)),h=Math.min(bitmapRef.current.height-y,Math.abs(dy));if(w>=1&&h>=1)setCrop({x:Math.round(x),y:Math.round(y),w:Math.round(w),h:Math.round(h)})}
  function applyRatio(next:typeof ratio){setRatio(next);const bitmap=bitmapRef.current;if(!bitmap||next==='free')return;const rv=next==='1:1'?1:next==='4:3'?4/3:next==='16:9'?16/9:9/16;let w=bitmap.width,h=Math.round(w/rv);if(h>bitmap.height){h=bitmap.height;w=Math.round(h*rv)}setCrop({x:Math.round((bitmap.width-w)/2),y:Math.round((bitmap.height-h)/2),w,h})}
  async function exportCrop(){const bitmap=bitmapRef.current;if(!bitmap||!file||crop.w<1||crop.h<1)return;const canvas=document.createElement('canvas');canvas.width=crop.w;canvas.height=crop.h;canvas.getContext('2d')!.drawImage(bitmap,crop.x,crop.y,crop.w,crop.h,0,0,crop.w,crop.h);const type=['image/jpeg','image/png','image/webp'].includes(file.type)?file.type:'image/png';const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Crop export failed.')),type,type==='image/png'?undefined:.92));const ext=type.split('/')[1].replace('jpeg','jpg');setResult({url:URL.createObjectURL(blob),name:file.name.replace(/\.[^.]+$/,'')+'-cropped.'+ext,before:file.size,after:blob.size})}
  return <div className="toolUi"><FileDrop accept="image/jpeg,image/png,image/webp" onChange={choose} label="Choose image" files={file?[file]:[]} busy={busy} busyLabel={busyLabel}/>{file&&<><div className="calcModeTabs unitTabs">{(['free','1:1','4:3','16:9','9:16'] as const).map(v=><button key={v} className={ratio===v?'active':''} onClick={()=>applyRatio(v)}>{v==='free'?'Free crop':v}</button>)}</div><div className="cropStage"><canvas ref={canvasRef} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={()=>{dragStart.current=null}} onPointerCancel={()=>{dragStart.current=null}}/><span>Drag across the image to draw a new crop area.</span></div><div className="fieldGrid cropFields"><label>X<input type="number" min="0" max={bitmapRef.current?.width||0} value={crop.x} onChange={e=>setCrop({...crop,x:+e.target.value})}/></label><label>Y<input type="number" min="0" max={bitmapRef.current?.height||0} value={crop.y} onChange={e=>setCrop({...crop,y:+e.target.value})}/></label><label>Width<input type="number" min="1" max={bitmapRef.current?.width||1} value={crop.w} onChange={e=>setCrop({...crop,w:+e.target.value})}/></label><label>Height<input type="number" min="1" max={bitmapRef.current?.height||1} value={crop.h} onChange={e=>setCrop({...crop,h:+e.target.value})}/></label></div><button className="primaryButton wide filePrimaryAction" onClick={exportCrop} disabled={busy}>{busy?'Cropping…':'Crop image'}</button></>}{error&&<div className="toolError">{error}</div>}{result&&<DownloadResult result={result}/>}</div>;
}

export function ImageExperience({tool}:{tool:Tool}){
  let ui=null;
  if(tool.kind==='image-convert')ui=<ImageConvert tool={tool}/>;
  else if(tool.kind==='image-compress')ui=<ImageCompress/>;
  else if(tool.kind==='image-compress-jpg')ui=<ImageCompressJpg/>;
  else if(tool.kind==='image-compress-png')ui=<ImageCompressPng/>;
  else if(tool.kind==='image-resize')ui=<ImageResize/>;
  else if(tool.kind==='image-crop')ui=<CropImage/>;
  else if(tool.kind==='heic-convert')ui=<HeicConverter/>;
  return <section className={`toolExperience accent-${tool.accent}`}><div className="experienceTop"><div><span className="eyebrow">TOOLMERA / {tool.categoryLabel.toUpperCase()}</span><div className="experienceTitle">{tool.name}</div></div><span className="privatePill"><ShieldCheck size={15}/> Browser-first processing</span></div>{ui}</section>;
}
