'use client';

import { useMemo, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import type { Tool } from '@/data/tools';

const money=(n:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
function MetricCard({label,value}:{label:string;value:string|number}){return <div className="metricCard"><span>{label}</span><strong>{value}</strong></div>}

function EmiIndiaCalculator({variant}:{variant:'generic'|'home'|'car'}){
  const [amount,setAmount]=useState(variant==='home'?5000000:variant==='car'?1200000:1000000),[downPayment,setDownPayment]=useState(variant==='car'?200000:0),[rate,setRate]=useState(variant==='home'?8.5:variant==='car'?9.5:9),[years,setYears]=useState(variant==='home'?20:5);
  const principal=variant==='car'?Math.max(0,amount-downPayment):amount;
  const result=useMemo(()=>{const n=Math.max(1,Math.round(years*12));if(principal<=0)return {error:'Enter a financed amount greater than zero.'} as const;if(rate<0)return {error:'Interest rate cannot be negative.'} as const;const r=rate/12/100,emi=r===0?principal/n:principal*r*(1+r)**n/((1+r)**n-1);let balance=principal;const yearly:{year:number;principal:number;interest:number;balance:number;payments:number}[]=[];let yp=0,yi=0,ypay=0;for(let month=1;month<=n;month++){const interest=balance*r,principalPaid=month===n?balance:Math.min(balance,emi-interest),payment=principalPaid+interest;balance=Math.max(0,balance-principalPaid);yp+=principalPaid;yi+=interest;ypay+=payment;if(month%12===0||month===n){yearly.push({year:Math.ceil(month/12),principal:yp,interest:yi,balance,payments:ypay});yp=0;yi=0;ypay=0}}const total=yearly.reduce((s,row)=>s+row.payments,0);return {emi,total,interest:total-principal,yearly,n}},[principal,rate,years]);
  return <div className="toolUi"><div className="fieldGrid batch5Fields">{variant==='car'?<><label>Vehicle / on-road price (₹)<input type="number" min="0" step="10000" value={amount} onChange={e=>setAmount(+e.target.value)}/></label><label>Down payment (₹)<input type="number" min="0" step="10000" value={downPayment} onChange={e=>setDownPayment(Math.max(0,+e.target.value))}/></label></>:<label>Loan amount (₹)<input type="number" min="0" step="10000" value={amount} onChange={e=>setAmount(+e.target.value)}/></label>}<label>Annual interest rate (%)<input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(+e.target.value)}/></label><label>Tenure (years)<input type="number" min="0.1" max={variant==='home'?50:20} step="0.5" value={years} onChange={e=>setYears(+e.target.value)}/></label></div>{variant==='car'&&<div className="formulaNote"><span>Financed principal</span><code>₹{money(principal)} = price − down payment</code></div>}{'error' in result?<div className="toolError">{result.error}</div>:<><div className="metricGrid compactMetrics"><MetricCard label="Monthly EMI" value={'₹'+money(result.emi)}/><MetricCard label="Total interest" value={'₹'+money(result.interest)}/><MetricCard label="Total repayment" value={'₹'+money(result.total)}/>{variant==='car'&&<MetricCard label="Financed amount" value={'₹'+money(principal)}/>}</div><div className="formulaNote"><span>Reducing-balance formula</span><code>EMI = P × r × (1+r)^n ÷ ((1+r)^n − 1)</code></div><div className="toolNote"><ShieldCheck size={15}/><span>{variant==='home'?'This is a constant-rate home-loan scenario. Floating-rate resets, fees, insurance, taxes and unscheduled prepayments can change the real repayment path.':variant==='car'?'The financed amount is modeled as vehicle price minus down payment. Processing fees, insurance, registration and other lender-specific charges are not added automatically.':'Fixed-rate reducing-balance estimate. Fees, insurance, rate resets and unscheduled prepayments are excluded.'}</span></div>{(variant==='home'||variant==='generic')&&<div className="growthTableWrap"><table className="growthTable"><thead><tr><th>Year</th><th>Payments</th><th>Principal</th><th>Interest</th><th>Balance</th></tr></thead><tbody>{result.yearly.map(row=><tr key={row.year}><td>{row.year}</td><td>₹{money(row.payments)}</td><td>₹{money(row.principal)}</td><td>₹{money(row.interest)}</td><td>₹{money(row.balance)}</td></tr>)}</tbody></table></div>}</>}</div>;
}

function SipIndiaCalculator(){
  const [monthly,setMonthly]=useState(10000),[annual,setAnnual]=useState(12),[years,setYears]=useState(10);
  const result=useMemo(()=>{const n=Math.max(1,Math.round(years*12)),r=annual/12/100,future=r===0?monthly*n:monthly*((1+r)**n-1)/r*(1+r),invested=monthly*n,rows=[];for(let year=1;year<=Math.ceil(n/12);year++){const months=Math.min(n,year*12),fv=r===0?monthly*months:monthly*((1+r)**months-1)/r*(1+r),inv=monthly*months;rows.push({year,invested:inv,value:fv,growth:fv-inv})}return {future,invested,growth:future-invested,rows}},[monthly,annual,years]);
  return <div className="toolUi"><div className="fieldGrid"><label>Monthly SIP (₹)<input type="number" min="0" step="500" value={monthly} onChange={e=>setMonthly(Math.max(0,+e.target.value))}/></label><label>Expected annual return (%)<input type="number" step="0.1" value={annual} onChange={e=>setAnnual(+e.target.value)}/></label><label>Investment period (years)<input type="number" min="0.1" max="60" step="0.5" value={years} onChange={e=>setYears(+e.target.value)}/></label></div><div className="metricGrid compactMetrics"><MetricCard label="Invested amount" value={'₹'+money(result.invested)}/><MetricCard label="Estimated growth" value={'₹'+money(result.growth)}/><MetricCard label="Projected value" value={'₹'+money(result.future)}/></div><div className="toolNote"><ShieldCheck size={15}/><span>Expected return is a planning assumption, not a guaranteed mutual-fund return. This projection excludes taxes, expense ratios, exit loads and real market volatility.</span></div><div className="growthTableWrap"><table className="growthTable"><thead><tr><th>Year</th><th>Invested</th><th>Estimated growth</th><th>Projected value</th></tr></thead><tbody>{result.rows.map(row=><tr key={row.year}><td>{row.year}</td><td>₹{money(row.invested)}</td><td>₹{money(row.growth)}</td><td>₹{money(row.value)}</td></tr>)}</tbody></table></div></div>;
}

function FdIndiaCalculator(){
  const [principal,setPrincipal]=useState(100000),[annual,setAnnual]=useState(7),[years,setYears]=useState(3),[frequency,setFrequency]=useState<1|2|4|12>(4);
  const result=useMemo(()=>{const maturity=principal*(1+annual/100/frequency)**(frequency*years);return {maturity,interest:maturity-principal}},[principal,annual,years,frequency]);
  return <div className="toolUi"><div className="fieldGrid batch5Fields"><label>Deposit amount (₹)<input type="number" min="0" step="1000" value={principal} onChange={e=>setPrincipal(Math.max(0,+e.target.value))}/></label><label>Annual interest rate (%)<input type="number" step="0.01" value={annual} onChange={e=>setAnnual(+e.target.value)}/></label><label>Term (years)<input type="number" min="0.1" max="50" step="0.25" value={years} onChange={e=>setYears(+e.target.value)}/></label><label>Compounding<select value={frequency} onChange={e=>setFrequency(+e.target.value as 1|2|4|12)}><option value={1}>Annually</option><option value={2}>Half-yearly</option><option value={4}>Quarterly</option><option value={12}>Monthly</option></select></label></div><div className="metricGrid compactMetrics"><MetricCard label="Maturity value" value={'₹'+money(result.maturity)}/><MetricCard label="Interest earned" value={'₹'+money(result.interest)}/><MetricCard label="Principal" value={'₹'+money(principal)}/></div><div className="formulaNote"><span>Compound model</span><code>A = P × (1 + r/m)^(m×t)</code></div><div className="toolNote"><ShieldCheck size={15}/><span>Use the compounding frequency stated by the actual deposit product. This is a gross mathematical estimate and does not model TDS, tax, premature-withdrawal adjustments or bank-specific rounding.</span></div></div>;
}

function GstIndiaCalculator(){
  const [mode,setMode]=useState<'add'|'remove'>('add'),[amount,setAmount]=useState(1000),[rate,setRate]=useState(18);
  const result=useMemo(()=>{if(mode==='add'){const gst=amount*rate/100;return {base:amount,gst,total:amount+gst}}const base=amount/(1+rate/100);return {base,gst:amount-base,total:amount}},[mode,amount,rate]);
  return <div className="toolUi"><div className="calcModeTabs unitTabs"><button className={mode==='add'?'active':''} onClick={()=>setMode('add')}>Add GST</button><button className={mode==='remove'?'active':''} onClick={()=>setMode('remove')}>Remove GST</button></div><div className="fieldGrid calculatorTwoFields"><label>{mode==='add'?'Base amount (₹)':'GST-inclusive amount (₹)'}<input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(Math.max(0,+e.target.value))}/></label><label>GST rate (%)<input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(Math.max(0,+e.target.value))}/></label></div><div className="quickPills">{[5,12,18,28].map(v=><button key={v} onClick={()=>setRate(v)}>{v}%</button>)}</div><div className="metricGrid compactMetrics"><MetricCard label="Base amount" value={'₹'+money(result.base)}/><MetricCard label="GST amount" value={'₹'+money(result.gst)}/><MetricCard label="GST-inclusive total" value={'₹'+money(result.total)}/></div><div className="formulaNote"><span>{mode==='add'?'Add GST':'Remove GST'}</span><code>{mode==='add'?'GST = Base × rate ÷ 100':'Base = Inclusive total ÷ (1 + rate/100)'}</code></div><div className="toolNote"><ShieldCheck size={15}/><span>The 5%, 12%, 18% and 28% buttons are common presets, not a classification decision. Verify the currently applicable GST rate for the specific goods or services using official CBIC/GST information.</span></div></div>;
}

function CagrCoreCalculator(){
  const [begin,setBegin]=useState(100000),[end,setEnd]=useState(200000),[years,setYears]=useState(5);const rate=begin>0&&end>=0&&years>0?((end/begin)**(1/years)-1)*100:null;
  return <div className="toolUi"><div className="fieldGrid"><label>Beginning value<input type="number" value={begin} onChange={e=>setBegin(+e.target.value)}/></label><label>Ending value<input type="number" value={end} onChange={e=>setEnd(+e.target.value)}/></label><label>Years<input type="number" min="0.01" step="0.1" value={years} onChange={e=>setYears(+e.target.value)}/></label></div><div className="metricGrid compactMetrics"><MetricCard label="CAGR" value={rate===null?'—':rate.toFixed(2)+'%'}/></div><div className="formulaNote"><span>Formula</span><code>CAGR = (Ending ÷ Beginning)^(1 ÷ Years) − 1</code></div></div>;
}

export function IndiaCalculatorsExperience({tool}:{tool:Tool}){
  let ui=null;
  if(tool.kind==='emi')ui=<EmiIndiaCalculator variant={tool.id==='home-emi-in'?'home':tool.id==='car-emi-in'?'car':'generic'}/>;
  else if(tool.kind==='sip')ui=<SipIndiaCalculator/>;
  else if(tool.kind==='fd')ui=<FdIndiaCalculator/>;
  else if(tool.kind==='gst')ui=<GstIndiaCalculator/>;
  else if(tool.kind==='cagr')ui=<CagrCoreCalculator/>;
  return <section className={`toolExperience accent-${tool.accent}`}><div className="experienceTop"><div><span className="eyebrow">TOOLMERA / {tool.categoryLabel.toUpperCase()}</span><div className="experienceTitle">{tool.name}</div></div><span className="privatePill"><ShieldCheck size={15}/> Browser-first processing</span></div>{ui}</section>;
}
