'use client';

import { useMemo, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import type { Tool } from '@/data/tools';
import { DownloadResult, FileDrop, FileQueue, Result } from './FileToolPrimitives';

function parsePageSet(input:string,pageCount:number){
  const clean=input.trim().toLowerCase();
  if(clean==='all')return new Set(Array.from({length:pageCount},(_,i)=>i));
  const out=new Set<number>();
  if(!clean)throw new Error('Enter page numbers such as 2, 5-9.');
  for(const part of clean.split(',').map(v=>v.trim()).filter(Boolean)){
    if(/^\d+$/.test(part)){const n=Number(part);if(n<1||n>pageCount)throw new Error('Page '+n+' is outside this '+pageCount+'-page PDF.');out.add(n-1);continue}
    const m=part.match(/^(\d+)\s*-\s*(\d+)$/);if(!m)throw new Error('Use page syntax such as 2, 5-9, 12.');
    const a=Number(m[1]),b=Number(m[2]);if(a<1||b<1||a>pageCount||b>pageCount)throw new Error('Range '+part+' is outside this '+pageCount+'-page PDF.');
    const lo=Math.min(a,b),hi=Math.max(a,b);for(let n=lo;n<=hi;n++)out.add(n-1);
  }
  return out;
}

function PdfRotate(){
  const [file,setFile]=useState<File|null>(null),[pageCount,setPageCount]=useState(0),[mode,setMode]=useState<'all'|'odd'|'even'|'custom'>('all'),[custom,setCustom]=useState('1'),[angle,setAngle]=useState<90|-90|180>(90),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[busyLabel,setBusyLabel]=useState('Reading PDF…'),[error,setError]=useState('');
  async function choose(files:File[]){if(!files[0])return;setFile(files[0]);setResult(null);setError('');setBusyLabel('Reading PDF…');setBusy(true);try{const {PDFDocument}=await import('pdf-lib'),doc=await PDFDocument.load(await files[0].arrayBuffer());setPageCount(doc.getPageCount())}catch{setPageCount(0);setError('Could not read this PDF. It may be encrypted or damaged.');setFile(null)}finally{setBusy(false)}}
  async function run(){if(!file)return;setBusyLabel('Rotating PDF…');setBusy(true);setError('');setResult(null);try{const {PDFDocument,degrees}=await import('pdf-lib'),doc=await PDFDocument.load(await file.arrayBuffer()),count=doc.getPageCount();const selected=mode==='all'?new Set(Array.from({length:count},(_,i)=>i)):mode==='odd'?new Set(Array.from({length:count},(_,i)=>i).filter(i=>i%2===0)):mode==='even'?new Set(Array.from({length:count},(_,i)=>i).filter(i=>i%2===1)):parsePageSet(custom,count);doc.getPages().forEach((page,i)=>{if(selected.has(i)){const next=((page.getRotation().angle+angle)%360+360)%360;page.setRotation(degrees(next))}});const bytes=await doc.save(),blob=new Blob([bytes as BlobPart],{type:'application/pdf'});setResult({url:URL.createObjectURL(blob),name:file.name.replace(/\.pdf$/i,'')+'-rotated.pdf',before:file.size,after:blob.size})}catch(e){setError(e instanceof Error?e.message:'Could not rotate this PDF.')}finally{setBusy(false)}}
  return <div className="toolUi"><FileDrop accept="application/pdf,.pdf" onChange={choose} label="Choose PDF file" files={file?[file]:[]} busy={busy} busyLabel={busyLabel}/>{file&&<><div className="calcModeTabs unitTabs">{(['all','odd','even','custom'] as const).map(v=><button key={v} className={mode===v?'active':''} onClick={()=>setMode(v)}>{v==='all'?'All pages':v==='odd'?'Odd pages':v==='even'?'Even pages':'Custom pages'}</button>)}</div>{mode==='custom'&&<label className="singleField">Pages to rotate<input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="2, 5-8"/></label>}<div className="calcModeTabs unitTabs"><button className={angle===90?'active':''} onClick={()=>setAngle(90)}>90° clockwise</button><button className={angle===-90?'active':''} onClick={()=>setAngle(-90)}>90° counter-clockwise</button><button className={angle===180?'active':''} onClick={()=>setAngle(180)}>180°</button></div><button className="primaryButton wide filePrimaryAction" onClick={run} disabled={busy}>{busy?'Rotating…':'Rotate PDF'}</button></>}{error&&<div className="toolError">{error}</div>}{result&&<DownloadResult result={result}/>}</div>;
}

function PdfRemovePages(){
  const [file,setFile]=useState<File|null>(null),[pageCount,setPageCount]=useState(0),[selection,setSelection]=useState('2'),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[busyLabel,setBusyLabel]=useState('Reading PDF…'),[error,setError]=useState('');
  async function choose(files:File[]){if(!files[0])return;setFile(files[0]);setResult(null);setError('');setBusyLabel('Reading PDF…');setBusy(true);try{const {PDFDocument}=await import('pdf-lib'),doc=await PDFDocument.load(await files[0].arrayBuffer());setPageCount(doc.getPageCount())}catch{setPageCount(0);setError('Could not read this PDF. It may be encrypted or damaged.');setFile(null)}finally{setBusy(false)}}
  const selectedCount=useMemo(()=>{try{return pageCount?parsePageSet(selection,pageCount).size:0}catch{return 0}},[selection,pageCount]);
  async function run(){if(!file)return;setBusyLabel('Removing PDF pages…');setBusy(true);setError('');setResult(null);try{const {PDFDocument}=await import('pdf-lib'),src=await PDFDocument.load(await file.arrayBuffer()),count=src.getPageCount(),remove=parsePageSet(selection,count);if(remove.size===0)throw new Error('Choose at least one page to remove.');if(remove.size>=count)throw new Error('A PDF must keep at least one page.');const keep=src.getPageIndices().filter(i=>!remove.has(i)),out=await PDFDocument.create(),pages=await out.copyPages(src,keep);pages.forEach(p=>out.addPage(p));const bytes=await out.save(),blob=new Blob([bytes as BlobPart],{type:'application/pdf'});setResult({url:URL.createObjectURL(blob),name:file.name.replace(/\.pdf$/i,'')+'-pages-removed.pdf',before:file.size,after:blob.size})}catch(e){setError(e instanceof Error?e.message:'Could not remove pages from this PDF.')}finally{setBusy(false)}}
  return <div className="toolUi"><FileDrop accept="application/pdf,.pdf" onChange={choose} label="Choose PDF file" files={file?[file]:[]} busy={busy} busyLabel={busyLabel}/>{file&&<><label className="singleField">Pages to remove<input value={selection} onChange={e=>setSelection(e.target.value)} placeholder="2, 5-9, 12"/></label>{pageCount>0&&<div className="toolNote"><ShieldCheck size={15}/><span>{selectedCount} page{selectedCount===1?'':'s'} selected for removal · {Math.max(0,pageCount-selectedCount)} page{pageCount-selectedCount===1?'':'s'} would remain.</span></div>}<button className="primaryButton wide filePrimaryAction" onClick={run} disabled={busy}>{busy?'Removing pages…':'Remove pages'}</button></>}{error&&<div className="toolError">{error}</div>}{result&&<DownloadResult result={result}/>}</div>;
}

function PdfToImage(){
  const [file,setFile]=useState<File|null>(null),[pageCount,setPageCount]=useState(0),[pages,setPages]=useState('all'),[format,setFormat]=useState<'jpg'|'png'>('jpg'),[scale,setScale]=useState(1.5),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[busyLabel,setBusyLabel]=useState('Reading PDF…'),[error,setError]=useState('');
  async function choose(files:File[]){if(!files[0])return;setFile(files[0]);setResult(null);setError('');setBusyLabel('Reading PDF…');setBusy(true);try{const {PDFDocument}=await import('pdf-lib'),doc=await PDFDocument.load(await files[0].arrayBuffer());setPageCount(doc.getPageCount())}catch{setPageCount(0);setError('Could not read this PDF. Password-protected or damaged PDFs are not supported in this converter.');setFile(null)}finally{setBusy(false)}}
  async function run(){if(!file)return;setBusyLabel('Rendering PDF pages…');setBusy(true);setError('');setResult(null);try{const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).toString();const loading=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}),pdf=await loading.promise,selected=[...parsePageSet(pages,pdf.numPages)].sort((a,b)=>a-b);if(!selected.length)throw new Error('Choose at least one PDF page.');const outputs:{name:string;blob:Blob}[]=[];for(const index of selected){const page=await pdf.getPage(index+1),viewport=page.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const ctx=canvas.getContext('2d')!;if(format==='jpg'){ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height)}await page.render({canvas,canvasContext:ctx,viewport}).promise;const mime=format==='jpg'?'image/jpeg':'image/png',blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Page rendering failed.')),mime,format==='jpg'?.9:undefined));outputs.push({name:file.name.replace(/\.pdf$/i,'')+'-page-'+(index+1)+'.'+format,blob});canvas.width=0;canvas.height=0;page.cleanup()}if(outputs.length===1){const out=outputs[0];setResult({url:URL.createObjectURL(out.blob),name:out.name,after:out.blob.size})}else{const JSZip=(await import('jszip')).default,zip=new JSZip();outputs.forEach(out=>zip.file(out.name,out.blob));const blob=await zip.generateAsync({type:'blob'});setResult({url:URL.createObjectURL(blob),name:file.name.replace(/\.pdf$/i,'')+'-images.zip',after:blob.size})}await loading.destroy()}catch(e){setError(e instanceof Error?e.message:'Could not convert this PDF to images.')}finally{setBusy(false)}}
  return <div className="toolUi"><FileDrop accept="application/pdf,.pdf" onChange={choose} label="Choose PDF file" files={file?[file]:[]} busy={busy} busyLabel={busyLabel}/>{file&&<><div className="calcModeTabs unitTabs"><button className={format==='jpg'?'active':''} onClick={()=>setFormat('jpg')}>JPG</button><button className={format==='png'?'active':''} onClick={()=>setFormat('png')}>PNG</button></div><div className="fieldGrid calculatorTwoFields"><label>Pages<input value={pages} onChange={e=>setPages(e.target.value)} placeholder="all or 1-3, 5"/></label><label>Render scale<select value={scale} onChange={e=>setScale(+e.target.value)}><option value={1}>1× compact</option><option value={1.5}>1.5× standard</option><option value={2}>2× sharp</option><option value={3}>3× high detail</option></select></label></div><div className="toolNote"><ShieldCheck size={15}/><span>Pages render sequentially to limit memory use. Multiple outputs are bundled into a ZIP. Password-protected PDFs are not supported in this version.</span></div><button className="primaryButton wide filePrimaryAction" onClick={run} disabled={busy}>{busy?'Rendering pages…':'Convert PDF to '+format.toUpperCase()}</button></>}{error&&<div className="toolError">{error}</div>}{result&&<DownloadResult result={result}/>}</div>;
}

function PdfTool({tool}:{tool:Tool}){
  const [files,setFiles]=useState<File[]>([]),[result,setResult]=useState<Result|null>(null),[range,setRange]=useState('1-1'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  function selectFiles(next:File[]){setFiles(next);setResult(null);setError('')}
  async function run(){if(!files.length)return;setBusy(true);setError('');setResult(null);try{const {PDFDocument}=await import('pdf-lib'),out=await PDFDocument.create();if(tool.kind==='pdf-merge'){for(const file of files){const src=await PDFDocument.load(await file.arrayBuffer()),pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p))}}if(tool.kind==='pdf-split'){const src=await PDFDocument.load(await files[0].arrayBuffer()),match=range.trim().match(/^(\d+)\s*-\s*(\d+)$/);if(!match)throw new Error('Use one page range, for example 4-9.');const a=Math.max(1,parseInt(match[1])),b=Math.max(1,parseInt(match[2])),start=Math.min(a,b)-1,end=Math.max(a,b)-1,indexes=src.getPageIndices().filter(i=>i>=start&&i<=end);if(!indexes.length)throw new Error(`That range is outside this PDF. It has ${src.getPageCount()} pages.`);const pages=await out.copyPages(src,indexes);pages.forEach(p=>out.addPage(p))}if(tool.kind==='images-to-pdf'){for(const file of files){const bytes=await file.arrayBuffer(),img=file.type==='image/png'?await out.embedPng(bytes):await out.embedJpg(bytes),page=out.addPage([img.width,img.height]);page.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}}const bytes=await out.save(),blob=new Blob([bytes as BlobPart],{type:'application/pdf'});setResult({url:URL.createObjectURL(blob),name:`toolmera-${tool.slug}.pdf`,after:blob.size})}catch(e){setError(e instanceof Error?e.message:'Could not process this file.')}finally{setBusy(false)}}
  const accept=tool.kind==='images-to-pdf'?(tool.inputFormat||'image/*'):'application/pdf',reorderable=tool.kind==='pdf-merge'||tool.kind==='images-to-pdf';
  return <div className="toolUi"><FileDrop accept={accept} multiple={tool.kind!=='pdf-split'} onChange={selectFiles} label="Choose files" files={files} busy={busy} busyLabel={tool.kind==='pdf-merge'?'Merging PDF files…':tool.kind==='pdf-split'?'Extracting PDF pages…':'Creating PDF…'}/>{reorderable&&files.length>0&&<><div className="queueHead"><span>Output order</span><small>Use the arrows to arrange files before creating the PDF.</small></div><FileQueue files={files} onChange={selectFiles}/></>}{tool.kind==='pdf-split'&&files.length>0&&<><label className="singleField">Page range<input value={range} onChange={e=>setRange(e.target.value)} placeholder="4-9"/></label><div className="toolNote"><ShieldCheck size={15}/><span>One continuous range per export, for example <b>4-9</b>. The source PDF is never modified.</span></div></>}{tool.kind==='images-to-pdf'&&files.length>0&&<div className="toolNote"><ShieldCheck size={15}/><span>Each image becomes one PDF page sized to that image&apos;s own dimensions.</span></div>}{error&&<div className="toolError">{error}</div>}<button className="primaryButton wide filePrimaryAction" onClick={run} disabled={!files.length||busy}>{busy?'Processing…':tool.name}</button>{result&&<DownloadResult result={result}/>}</div>;
}

export function PdfExperience({tool}:{tool:Tool}){
  let ui=null;
  if(tool.kind==='pdf-to-image')ui=<PdfToImage/>;
  else if(tool.kind==='pdf-rotate')ui=<PdfRotate/>;
  else if(tool.kind==='pdf-remove-pages')ui=<PdfRemovePages/>;
  else if(['pdf-merge','pdf-split','images-to-pdf'].includes(tool.kind))ui=<PdfTool tool={tool}/>;
  return <section className={`toolExperience accent-${tool.accent}`}><div className="experienceTop"><div><span className="eyebrow">TOOLMERA / {tool.categoryLabel.toUpperCase()}</span><div className="experienceTitle">{tool.name}</div></div><span className="privatePill"><ShieldCheck size={15}/> Browser-first processing</span></div>{ui}</section>;
}
