'use client';

import { useMemo, useState } from 'react';
import { Check, Copy, ShieldCheck } from 'lucide-react';
import type { Tool } from '@/data/tools';

function MetricCard({label,value,suffix='' }:{label:string;value:string|number;suffix?:string}){return <div className="metricCard"><span>{label}</span><strong>{value}{suffix}</strong></div>}
async function copyPlainText(value:string){await navigator.clipboard.writeText(value)}

function countWords(text:string){if(!text.trim())return 0;const Segmenter=(Intl as typeof Intl & {Segmenter?:new(...args:any[])=>any}).Segmenter;if(Segmenter){const segmenter=new Segmenter(undefined,{granularity:'word'});return Array.from(segmenter.segment(text)).filter((s:any)=>s.isWordLike).length}return text.trim().split(/\s+/).length}
function countSentences(text:string){if(!text.trim())return 0;const Segmenter=(Intl as typeof Intl & {Segmenter?:new(...args:any[])=>any}).Segmenter;if(Segmenter){const segmenter=new Segmenter(undefined,{granularity:'sentence'});return Array.from(segmenter.segment(text)).filter((s:any)=>s.segment.trim()).length}return text.split(/[.!?]+/).filter(s=>s.trim()).length}

function WordCounter(){
  const [text,setText]=useState('');const words=useMemo(()=>countWords(text),[text]);const chars=useMemo(()=>Array.from(text).length,[text]);const charsNoSpaces=useMemo(()=>Array.from(text.replace(/\s/g,'')).length,[text]);const sentences=useMemo(()=>countSentences(text),[text]);const paragraphs=useMemo(()=>text.trim()?text.trim().split(/\n\s*\n+/).filter(p=>p.trim()).length:0,[text]);const reading=words?Math.max(1,Math.ceil(words/220)):0;
  return <div className="toolUi"><textarea className="textArea" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste or type here…"/><div className="metricGrid textMetricGrid"><MetricCard label="Words" value={words}/><MetricCard label="Characters" value={chars}/><MetricCard label="No spaces" value={charsNoSpaces}/><MetricCard label="Sentences" value={sentences}/><MetricCard label="Paragraphs" value={paragraphs}/><MetricCard label="Reading time" value={reading} suffix=" min"/></div><div className="toolNote"><ShieldCheck size={15}/><span>Reading time uses an estimated 220 words per minute. Sentence and word segmentation use the browser&apos;s language-aware segmenter when available.</span></div></div>;
}

function normalizeCaseWords(text:string){return text.replace(/([a-z0-9])([A-Z])/g,'$1 $2').trim().split(/[\s_-]+/).map(w=>w.replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu,'')).filter(Boolean)}
function simpleTitleCase(text:string){return text.toLocaleLowerCase().replace(/\b(\p{L})/gu,m=>m.toLocaleUpperCase())}
function sentenceCase(text:string){const lower=text.toLocaleLowerCase();return lower.replace(/(^|[.!?]\s+)(\p{L})/gu,(_,prefix,letter)=>prefix+letter.toLocaleUpperCase())}
function CaseConverter(){
  const [text,setText]=useState(''),[output,setOutput]=useState(''),[copied,setCopied]=useState(false);
  function action(type:string){const words=normalizeCaseWords(text);if(type==='upper')setOutput(text.toLocaleUpperCase());if(type==='lower')setOutput(text.toLocaleLowerCase());if(type==='title')setOutput(simpleTitleCase(text));if(type==='sentence')setOutput(sentenceCase(text));if(type==='camel')setOutput(words.map((w,i)=>i===0?w.toLocaleLowerCase():w.charAt(0).toLocaleUpperCase()+w.slice(1).toLocaleLowerCase()).join(''));if(type==='pascal')setOutput(words.map(w=>w.charAt(0).toLocaleUpperCase()+w.slice(1).toLocaleLowerCase()).join(''));if(type==='snake')setOutput(words.map(w=>w.toLocaleLowerCase()).join('_'));if(type==='kebab')setOutput(words.map(w=>w.toLocaleLowerCase()).join('-'));if(type==='constant')setOutput(words.map(w=>w.toLocaleUpperCase()).join('_'));setCopied(false)}
  async function copy(){if(!output)return;await copyPlainText(output);setCopied(true);window.setTimeout(()=>setCopied(false),1400)}
  return <div className="toolUi"><textarea className="textArea" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste or type here…"/><div className="buttonRow caseButtons"><button className="secondaryButton" onClick={()=>action('upper')}>UPPERCASE</button><button className="secondaryButton" onClick={()=>action('lower')}>lowercase</button><button className="secondaryButton" onClick={()=>action('title')}>Simple Title Case</button><button className="secondaryButton" onClick={()=>action('sentence')}>Sentence case</button><button className="secondaryButton" onClick={()=>action('camel')}>camelCase</button><button className="secondaryButton" onClick={()=>action('pascal')}>PascalCase</button><button className="secondaryButton" onClick={()=>action('snake')}>snake_case</button><button className="secondaryButton" onClick={()=>action('kebab')}>kebab-case</button><button className="secondaryButton" onClick={()=>action('constant')}>CONSTANT_CASE</button></div><div className="outputWrap"><textarea className="textArea output" readOnly value={output} placeholder="Result…"/><button className="copyButton" onClick={copy} disabled={!output}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy'}</button></div><div className="toolNote"><ShieldCheck size={15}/><span>“Simple Title Case” capitalizes every word. It does not apply AP, Chicago, APA or other editorial minor-word rules.</span></div></div>;
}

function graphemeLength(value:string){const Segmenter=(Intl as typeof Intl & {Segmenter?:new(...args:any[])=>any}).Segmenter;if(Segmenter)return Array.from(new Segmenter(undefined,{granularity:'grapheme'}).segment(value)).length;return Array.from(value).length}
function CharacterCounter(){const [text,setText]=useState('');const characters=useMemo(()=>graphemeLength(text),[text]);const noWhitespace=useMemo(()=>graphemeLength(text.replace(/\s/gu,'')),[text]);const spaces=useMemo(()=>graphemeLength(text.match(/\s/gu)?.join('')||''),[text]);const lines=useMemo(()=>text?text.split(/\r\n|\r|\n/).length:0,[text]);const words=useMemo(()=>countWords(text),[text]);const bytes=useMemo(()=>new TextEncoder().encode(text).length,[text]);return <div className="toolUi"><textarea className="textArea" value={text} onChange={x=>setText(x.target.value)} placeholder="Paste or type text here…"/><div className="metricGrid textMetricGrid"><MetricCard label="Characters" value={characters}/><MetricCard label="No whitespace" value={noWhitespace}/><MetricCard label="Whitespace" value={spaces}/><MetricCard label="Words" value={words}/><MetricCard label="Lines" value={lines}/><MetricCard label="UTF-8 bytes" value={bytes}/></div><div className="toolNote"><ShieldCheck size={15}/><span>Character counting uses Unicode grapheme segmentation when the browser supports it. UTF-8 bytes are a separate storage measurement and can exceed the visible character count.</span></div></div>}

function RemoveDuplicateLines(){
  const [text,setText]=useState(''),[ignoreCase,setIgnoreCase]=useState(false),[trim,setTrim]=useState(true),[removeBlank,setRemoveBlank]=useState(true),[sort,setSort]=useState<'preserve'|'az'|'za'>('preserve'),[copied,setCopied]=useState(false);
  const result=useMemo(()=>{const input=text?text.split(/\r\n|\r|\n/):[];const seen=new Set<string>();const unique:string[]=[];for(const raw of input){const value=trim?raw.trim():raw;if(removeBlank&&!value)continue;const key=ignoreCase?value.toLocaleLowerCase():value;if(seen.has(key))continue;seen.add(key);unique.push(value)}if(sort!=='preserve'){const collator=new Intl.Collator(undefined,{numeric:true,sensitivity:ignoreCase?'base':'variant'});unique.sort((a,b)=>sort==='az'?collator.compare(a,b):collator.compare(b,a))}return {output:unique.join('\n'),inputCount:input.length,uniqueCount:unique.length}},[text,ignoreCase,trim,removeBlank,sort]);
  async function copy(){if(!result.output)return;await copyPlainText(result.output);setCopied(true);window.setTimeout(()=>setCopied(false),1200)}
  return <div className="toolUi"><textarea className="textArea" value={text} onChange={x=>setText(x.target.value)} placeholder={'apple\nbanana\napple\nAPPLE'}/><div className="fieldGrid generatorFields"><label>Order<select value={sort} onChange={x=>setSort(x.target.value as 'preserve'|'az'|'za')}><option value="preserve">Preserve input order</option><option value="az">Sort A–Z</option><option value="za">Sort Z–A</option></select></label><label className="checkControl"><input type="checkbox" checked={ignoreCase} onChange={x=>setIgnoreCase(x.target.checked)}/><span>Ignore case</span></label><label className="checkControl"><input type="checkbox" checked={trim} onChange={x=>setTrim(x.target.checked)}/><span>Trim whitespace</span></label><label className="checkControl"><input type="checkbox" checked={removeBlank} onChange={x=>setRemoveBlank(x.target.checked)}/><span>Remove blank lines</span></label></div><div className="metricGrid textMetricGrid"><MetricCard label="Input lines" value={result.inputCount}/><MetricCard label="Unique lines" value={result.uniqueCount}/><MetricCard label="Removed" value={Math.max(0,result.inputCount-result.uniqueCount)}/></div><div className="outputWrap"><textarea className="textArea output" readOnly value={result.output} placeholder="Unique lines appear here…"/><button className="copyButton" onClick={copy} disabled={!result.output}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy'}</button></div></div>;
}

function SortLines(){
  const [text,setText]=useState(''),[direction,setDirection]=useState<'asc'|'desc'>('asc'),[natural,setNatural]=useState(true),[ignoreCase,setIgnoreCase]=useState(true),[removeBlank,setRemoveBlank]=useState(true),[copied,setCopied]=useState(false);
  const output=useMemo(()=>{const lines=(text?text.split(/\r\n|\r|\n/):[]).filter(x=>!removeBlank||x.trim());const collator=new Intl.Collator(undefined,{numeric:natural,sensitivity:ignoreCase?'base':'variant'});return [...lines].sort((a,b)=>direction==='asc'?collator.compare(a,b):collator.compare(b,a)).join('\n')},[text,direction,natural,ignoreCase,removeBlank]);
  async function copy(){if(!output)return;await copyPlainText(output);setCopied(true);window.setTimeout(()=>setCopied(false),1200)}
  return <div className="toolUi"><textarea className="textArea" value={text} onChange={x=>setText(x.target.value)} placeholder={'file10\nfile2\nfile1'}/><div className="fieldGrid generatorFields"><label>Direction<select value={direction} onChange={x=>setDirection(x.target.value as 'asc'|'desc')}><option value="asc">A → Z</option><option value="desc">Z → A</option></select></label><label className="checkControl"><input type="checkbox" checked={natural} onChange={x=>setNatural(x.target.checked)}/><span>Natural numeric sort</span></label><label className="checkControl"><input type="checkbox" checked={ignoreCase} onChange={x=>setIgnoreCase(x.target.checked)}/><span>Ignore case</span></label><label className="checkControl"><input type="checkbox" checked={removeBlank} onChange={x=>setRemoveBlank(x.target.checked)}/><span>Remove blank lines</span></label></div><div className="outputWrap"><textarea className="textArea output" readOnly value={output} placeholder="Sorted lines appear here…"/><button className="copyButton" onClick={copy} disabled={!output}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy'}</button></div></div>;
}

type LineDiffItem={type:'same'|'add'|'remove';text:string};
function buildLineDiff(left:string,right:string){const a=left.split(/\r\n|\r|\n/),b=right.split(/\r\n|\r|\n/);if(a.length>600||b.length>600)throw new Error('For a responsive browser diff, keep each side to 600 lines or fewer.');const dp=Array.from({length:a.length+1},()=>new Uint16Array(b.length+1));for(let i=a.length-1;i>=0;i--)for(let j=b.length-1;j>=0;j--)dp[i][j]=a[i]===b[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);const items:LineDiffItem[]=[];let i=0,j=0;while(i<a.length&&j<b.length){if(a[i]===b[j]){items.push({type:'same',text:a[i]});i++;j++;continue}if(dp[i+1][j]>=dp[i][j+1]){items.push({type:'remove',text:a[i]});i++}else{items.push({type:'add',text:b[j]});j++}}while(i<a.length)items.push({type:'remove',text:a[i++]});while(j<b.length)items.push({type:'add',text:b[j++]});return items}
function TextDiffChecker(){
  const [left,setLeft]=useState(''),[right,setRight]=useState(''),[copied,setCopied]=useState(false);
  const result=useMemo(()=>{if(!left&&!right)return {output:'',added:0,removed:0,unchanged:0,error:''};try{const items=buildLineDiff(left,right);return {output:items.map(x=>(x.type==='add'?'+ ':x.type==='remove'?'- ':'  ')+x.text).join('\n'),added:items.filter(x=>x.type==='add').length,removed:items.filter(x=>x.type==='remove').length,unchanged:items.filter(x=>x.type==='same').length,error:''}}catch(err){return {output:'',added:0,removed:0,unchanged:0,error:err instanceof Error?err.message:'Could not compare these texts.'}}},[left,right]);
  async function copy(){if(!result.output)return;await copyPlainText(result.output);setCopied(true);window.setTimeout(()=>setCopied(false),1200)}
  return <div className="toolUi"><div className="jwtGrid"><div><div className="queueHead"><span>Original</span></div><textarea className="textArea codeArea" value={left} onChange={x=>setLeft(x.target.value)} placeholder="Original text…"/></div><div><div className="queueHead"><span>Changed</span></div><textarea className="textArea codeArea" value={right} onChange={x=>setRight(x.target.value)} placeholder="Changed text…"/></div></div>{result.error&&<div className="toolError">{result.error}</div>}<div className="metricGrid textMetricGrid"><MetricCard label="Added" value={result.added}/><MetricCard label="Removed" value={result.removed}/><MetricCard label="Unchanged" value={result.unchanged}/></div><div className="outputWrap"><textarea className="textArea output codeArea" readOnly value={result.output} placeholder="+ added, - removed and unchanged lines appear here…"/><button className="copyButton" onClick={copy} disabled={!result.output}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy'}</button></div><div className="toolNote"><ShieldCheck size={15}/><span>This is a line-level longest-common-subsequence diff, optimized for pasted text and small configuration files rather than very large repositories.</span></div></div>;
}

export function TextExperience({tool}:{tool:Tool}){
  let ui=null;
  if(tool.kind==='word-counter')ui=<WordCounter/>;
  else if(tool.kind==='case-converter')ui=<CaseConverter/>;
  else if(tool.kind==='character-counter')ui=<CharacterCounter/>;
  else if(tool.kind==='remove-duplicate-lines')ui=<RemoveDuplicateLines/>;
  else if(tool.kind==='sort-lines')ui=<SortLines/>;
  else if(tool.kind==='text-diff')ui=<TextDiffChecker/>;
  return <section className={`toolExperience accent-${tool.accent}`}><div className="experienceTop"><div><span className="eyebrow">TOOLMERA / {tool.categoryLabel.toUpperCase()}</span><div className="experienceTitle">{tool.name}</div></div><span className="privatePill"><ShieldCheck size={15}/> Browser-first processing</span></div>{ui}</section>;
}
